//// [es6ImportNamedImportWithExport.ts] ////

//// [client.d.ts.map]
{
  "version": 3,
  "file": "client.d.ts",
  "sourceRoot": "",
  "sources": [
    "client.ts"
  ],
  "names": [],
  "mappings": [
    {
      "generatedLine": 1,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 3,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 1,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 3,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 1,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 3,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 1,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 3,
      "originalColumn": 15,
      "name": null,
      "generatedText": "xxxx",
      "sourceText": "xxxx"
    },
    {
      "generatedLine": 1,
      "generatedColumn": 25,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 3,
      "originalColumn": 17,
      "name": null,
      "generatedText": ": ",
      "sourceText": ": "
    },
    {
      "generatedLine": 1,
      "generatedColumn": 31,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 3,
      "originalColumn": 27,
      "name": null,
      "generatedText": "number",
      "sourceText": "number = a"
    },
    {
      "generatedLine": 1,
      "generatedColumn": 32,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 3,
      "originalColumn": 28,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 2,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 5,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 2,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 5,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 2,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 5,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 2,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 5,
      "originalColumn": 15,
      "name": null,
      "generatedText": "xxxx",
      "sourceText": "xxxx"
    },
    {
      "generatedLine": 2,
      "generatedColumn": 31,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 5,
      "originalColumn": 19,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = b"
    },
    {
      "generatedLine": 2,
      "generatedColumn": 32,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 5,
      "originalColumn": 20,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 3,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 7,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 3,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 7,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 3,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 7,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 3,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 7,
      "originalColumn": 15,
      "name": null,
      "generatedText": "xxxx",
      "sourceText": "xxxx"
    },
    {
      "generatedLine": 3,
      "generatedColumn": 31,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 7,
      "originalColumn": 19,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = x"
    },
    {
      "generatedLine": 3,
      "generatedColumn": 32,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 7,
      "originalColumn": 20,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 4,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 8,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 4,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 8,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 4,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 8,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 4,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 8,
      "originalColumn": 15,
      "name": null,
      "generatedText": "xxxx",
      "sourceText": "xxxx"
    },
    {
      "generatedLine": 4,
      "generatedColumn": 31,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 8,
      "originalColumn": 19,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = y"
    },
    {
      "generatedLine": 4,
      "generatedColumn": 32,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 8,
      "originalColumn": 20,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 5,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 10,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 5,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 10,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 5,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 10,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 5,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 10,
      "originalColumn": 15,
      "name": null,
      "generatedText": "xxxx",
      "sourceText": "xxxx"
    },
    {
      "generatedLine": 5,
      "generatedColumn": 31,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 10,
      "originalColumn": 19,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = z"
    },
    {
      "generatedLine": 5,
      "generatedColumn": 32,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 10,
      "originalColumn": 20,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 6,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 12,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 6,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 12,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 6,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 12,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 6,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 12,
      "originalColumn": 15,
      "name": null,
      "generatedText": "xxxx",
      "sourceText": "xxxx"
    },
    {
      "generatedLine": 6,
      "generatedColumn": 31,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 12,
      "originalColumn": 19,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = m"
    },
    {
      "generatedLine": 6,
      "generatedColumn": 32,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 12,
      "originalColumn": 20,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 7,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 14,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 7,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 14,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 7,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 14,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 7,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 14,
      "originalColumn": 15,
      "name": null,
      "generatedText": "xxxx",
      "sourceText": "xxxx"
    },
    {
      "generatedLine": 7,
      "generatedColumn": 31,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 14,
      "originalColumn": 20,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = a1"
    },
    {
      "generatedLine": 7,
      "generatedColumn": 32,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 14,
      "originalColumn": 21,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 8,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 15,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 8,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 15,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 8,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 15,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 8,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 15,
      "originalColumn": 15,
      "name": null,
      "generatedText": "xxxx",
      "sourceText": "xxxx"
    },
    {
      "generatedLine": 8,
      "generatedColumn": 31,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 15,
      "originalColumn": 20,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = x1"
    },
    {
      "generatedLine": 8,
      "generatedColumn": 32,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 15,
      "originalColumn": 21,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 9,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 17,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 9,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 17,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 9,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 17,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 9,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 17,
      "originalColumn": 15,
      "name": null,
      "generatedText": "xxxx",
      "sourceText": "xxxx"
    },
    {
      "generatedLine": 9,
      "generatedColumn": 31,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 17,
      "originalColumn": 21,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = a11"
    },
    {
      "generatedLine": 9,
      "generatedColumn": 32,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 17,
      "originalColumn": 22,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 10,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 18,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 10,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 18,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 10,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 18,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 10,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 18,
      "originalColumn": 15,
      "name": null,
      "generatedText": "xxxx",
      "sourceText": "xxxx"
    },
    {
      "generatedLine": 10,
      "generatedColumn": 31,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 18,
      "originalColumn": 21,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = x11"
    },
    {
      "generatedLine": 10,
      "generatedColumn": 32,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 18,
      "originalColumn": 22,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 11,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 20,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 11,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 20,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 11,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 20,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 11,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 20,
      "originalColumn": 15,
      "name": null,
      "generatedText": "z111",
      "sourceText": "z111"
    },
    {
      "generatedLine": 11,
      "generatedColumn": 25,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 20,
      "originalColumn": 17,
      "name": null,
      "generatedText": ": ",
      "sourceText": ": "
    },
    {
      "generatedLine": 11,
      "generatedColumn": 31,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 20,
      "originalColumn": 28,
      "name": null,
      "generatedText": "number",
      "sourceText": "number = z1"
    },
    {
      "generatedLine": 11,
      "generatedColumn": 32,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 20,
      "originalColumn": 29,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 12,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 22,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 12,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 22,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 12,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 22,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 12,
      "generatedColumn": 21,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 22,
      "originalColumn": 13,
      "name": null,
      "generatedText": "z2",
      "sourceText": "z2"
    },
    {
      "generatedLine": 12,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 22,
      "originalColumn": 15,
      "name": null,
      "generatedText": ": ",
      "sourceText": ": "
    },
    {
      "generatedLine": 12,
      "generatedColumn": 29,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 22,
      "originalColumn": 26,
      "name": null,
      "generatedText": "number",
      "sourceText": "number = z3"
    },
    {
      "generatedLine": 12,
      "generatedColumn": 30,
      "lastGeneratedColumn": null,
      "source": "client.ts",
      "originalLine": 22,
      "originalColumn": 27,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    }
  ]
}//// [server.d.ts.map]
{
  "version": 3,
  "file": "server.d.ts",
  "sourceRoot": "",
  "sources": [
    "server.ts"
  ],
  "names": [],
  "mappings": [
    {
      "generatedLine": 1,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 1,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 1,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 1,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 1,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 1,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 1,
      "generatedColumn": 20,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 1,
      "originalColumn": 12,
      "name": null,
      "generatedText": "a",
      "sourceText": "a"
    },
    {
      "generatedLine": 1,
      "generatedColumn": 28,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 1,
      "originalColumn": 17,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = 10"
    },
    {
      "generatedLine": 1,
      "generatedColumn": 29,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 1,
      "originalColumn": 18,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 2,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 2,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 2,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 2,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 2,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 2,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 2,
      "generatedColumn": 20,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 2,
      "originalColumn": 12,
      "name": null,
      "generatedText": "x",
      "sourceText": "x"
    },
    {
      "generatedLine": 2,
      "generatedColumn": 22,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 2,
      "originalColumn": 14,
      "name": null,
      "generatedText": ": ",
      "sourceText": ": "
    },
    {
      "generatedLine": 2,
      "generatedColumn": 28,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 2,
      "originalColumn": 24,
      "name": null,
      "generatedText": "number",
      "sourceText": "number = a"
    },
    {
      "generatedLine": 2,
      "generatedColumn": 29,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 2,
      "originalColumn": 25,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 3,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 3,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 3,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 3,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 3,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 3,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 3,
      "generatedColumn": 20,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 3,
      "originalColumn": 12,
      "name": null,
      "generatedText": "m",
      "sourceText": "m"
    },
    {
      "generatedLine": 3,
      "generatedColumn": 22,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 3,
      "originalColumn": 14,
      "name": null,
      "generatedText": ": ",
      "sourceText": ": "
    },
    {
      "generatedLine": 3,
      "generatedColumn": 28,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 3,
      "originalColumn": 24,
      "name": null,
      "generatedText": "number",
      "sourceText": "number = a"
    },
    {
      "generatedLine": 3,
      "generatedColumn": 29,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 3,
      "originalColumn": 25,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 4,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 4,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 4,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 4,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 4,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 4,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 4,
      "generatedColumn": 21,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 4,
      "originalColumn": 13,
      "name": null,
      "generatedText": "a1",
      "sourceText": "a1"
    },
    {
      "generatedLine": 4,
      "generatedColumn": 29,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 4,
      "originalColumn": 18,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = 10"
    },
    {
      "generatedLine": 4,
      "generatedColumn": 30,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 4,
      "originalColumn": 19,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 5,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 5,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 5,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 5,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 5,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 5,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 5,
      "generatedColumn": 21,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 5,
      "originalColumn": 13,
      "name": null,
      "generatedText": "x1",
      "sourceText": "x1"
    },
    {
      "generatedLine": 5,
      "generatedColumn": 29,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 5,
      "originalColumn": 18,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = 10"
    },
    {
      "generatedLine": 5,
      "generatedColumn": 30,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 5,
      "originalColumn": 19,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 6,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 6,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 6,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 6,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 6,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 6,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 6,
      "generatedColumn": 21,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 6,
      "originalColumn": 13,
      "name": null,
      "generatedText": "z1",
      "sourceText": "z1"
    },
    {
      "generatedLine": 6,
      "generatedColumn": 29,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 6,
      "originalColumn": 18,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = 10"
    },
    {
      "generatedLine": 6,
      "generatedColumn": 30,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 6,
      "originalColumn": 19,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 7,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 7,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 7,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 7,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 7,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 7,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 7,
      "generatedColumn": 21,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 7,
      "originalColumn": 13,
      "name": null,
      "generatedText": "z2",
      "sourceText": "z2"
    },
    {
      "generatedLine": 7,
      "generatedColumn": 29,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 7,
      "originalColumn": 18,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = 10"
    },
    {
      "generatedLine": 7,
      "generatedColumn": 30,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 7,
      "originalColumn": 19,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    },
    {
      "generatedLine": 8,
      "generatedColumn": 0,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 8,
      "originalColumn": 0,
      "name": null
    },
    {
      "generatedLine": 8,
      "generatedColumn": 15,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 8,
      "originalColumn": 7,
      "name": null,
      "generatedText": "export declare ",
      "sourceText": "export "
    },
    {
      "generatedLine": 8,
      "generatedColumn": 19,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 8,
      "originalColumn": 11,
      "name": null,
      "generatedText": "var ",
      "sourceText": "var "
    },
    {
      "generatedLine": 8,
      "generatedColumn": 23,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 8,
      "originalColumn": 15,
      "name": null,
      "generatedText": "aaaa",
      "sourceText": "aaaa"
    },
    {
      "generatedLine": 8,
      "generatedColumn": 31,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 8,
      "originalColumn": 20,
      "name": null,
      "generatedText": ": number",
      "sourceText": " = 10"
    },
    {
      "generatedLine": 8,
      "generatedColumn": 32,
      "lastGeneratedColumn": null,
      "source": "server.ts",
      "originalLine": 8,
      "originalColumn": 21,
      "name": null,
      "generatedText": ";",
      "sourceText": ";"
    }
  ]
}