// Code generated by tools/scripts/tsc/generate-options.ts. DO NOT EDIT.

package tsoptions

import "github.com/microsoft/TypeScript/tsc/internal/core"

// ForEachCompilerOptionAffectingBuildInfo visits nonzero options in CompilerOptions field order.
func ForEachCompilerOptionAffectingBuildInfo(options *core.CompilerOptions, fn func(option *CommandLineOption, value any)) {
	if options.AllowJs != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("allowJs"), options.AllowJs)
	}
	if options.AllowImportingTsExtensions != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("allowImportingTsExtensions"), options.AllowImportingTsExtensions)
	}
	if options.AllowUmdGlobalAccess != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("allowUmdGlobalAccess"), options.AllowUmdGlobalAccess)
	}
	if options.AllowUnreachableCode != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("allowUnreachableCode"), options.AllowUnreachableCode)
	}
	if options.AllowUnusedLabels != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("allowUnusedLabels"), options.AllowUnusedLabels)
	}
	if options.AssumeChangesOnlyAffectDirectDependencies != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("assumeChangesOnlyAffectDirectDependencies"), options.AssumeChangesOnlyAffectDirectDependencies)
	}
	if options.CheckJs != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("checkJs"), options.CheckJs)
	}
	if options.Composite != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("composite"), options.Composite)
	}
	if options.EmitDeclarationOnly != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("emitDeclarationOnly"), options.EmitDeclarationOnly)
	}
	if options.EmitBOM != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("emitBOM"), options.EmitBOM)
	}
	if options.EmitDecoratorMetadata != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("emitDecoratorMetadata"), options.EmitDecoratorMetadata)
	}
	if options.Declaration != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("declaration"), options.Declaration)
	}
	if options.DeclarationDir != "" {
		fn(CommandLineCompilerOptionsMap.Get("declarationDir"), options.DeclarationDir)
	}
	if options.DeclarationMap != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("declarationMap"), options.DeclarationMap)
	}
	if options.ErasableSyntaxOnly != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("erasableSyntaxOnly"), options.ErasableSyntaxOnly)
	}
	if options.ExactOptionalPropertyTypes != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("exactOptionalPropertyTypes"), options.ExactOptionalPropertyTypes)
	}
	if options.ExperimentalDecorators != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("experimentalDecorators"), options.ExperimentalDecorators)
	}
	if options.IsolatedDeclarations != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("isolatedDeclarations"), options.IsolatedDeclarations)
	}
	if options.ImportHelpers != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("importHelpers"), options.ImportHelpers)
	}
	if options.InlineSourceMap != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("inlineSourceMap"), options.InlineSourceMap)
	}
	if options.InlineSources != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("inlineSources"), options.InlineSources)
	}
	if options.Jsx != 0 {
		fn(CommandLineCompilerOptionsMap.Get("jsx"), options.Jsx)
	}
	if options.JsxImportSource != "" {
		fn(CommandLineCompilerOptionsMap.Get("jsxImportSource"), options.JsxImportSource)
	}
	if options.MapRoot != "" {
		fn(CommandLineCompilerOptionsMap.Get("mapRoot"), options.MapRoot)
	}
	if options.Module != 0 {
		fn(CommandLineCompilerOptionsMap.Get("module"), options.Module)
	}
	if options.NewLine != 0 {
		fn(CommandLineCompilerOptionsMap.Get("newLine"), options.NewLine)
	}
	if options.NoErrorTruncation != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noErrorTruncation"), options.NoErrorTruncation)
	}
	if options.NoFallthroughCasesInSwitch != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noFallthroughCasesInSwitch"), options.NoFallthroughCasesInSwitch)
	}
	if options.NoImplicitAny != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noImplicitAny"), options.NoImplicitAny)
	}
	if options.NoImplicitThis != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noImplicitThis"), options.NoImplicitThis)
	}
	if options.NoImplicitReturns != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noImplicitReturns"), options.NoImplicitReturns)
	}
	if options.NoEmitHelpers != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noEmitHelpers"), options.NoEmitHelpers)
	}
	if options.NoPropertyAccessFromIndexSignature != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noPropertyAccessFromIndexSignature"), options.NoPropertyAccessFromIndexSignature)
	}
	if options.NoUncheckedIndexedAccess != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noUncheckedIndexedAccess"), options.NoUncheckedIndexedAccess)
	}
	if options.NoEmitOnError != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noEmitOnError"), options.NoEmitOnError)
	}
	if options.NoUnusedLocals != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noUnusedLocals"), options.NoUnusedLocals)
	}
	if options.NoUnusedParameters != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noUnusedParameters"), options.NoUnusedParameters)
	}
	if options.NoImplicitOverride != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noImplicitOverride"), options.NoImplicitOverride)
	}
	if options.NoUncheckedSideEffectImports != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("noUncheckedSideEffectImports"), options.NoUncheckedSideEffectImports)
	}
	if options.OutDir != "" {
		fn(CommandLineCompilerOptionsMap.Get("outDir"), options.OutDir)
	}
	if options.PreserveConstEnums != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("preserveConstEnums"), options.PreserveConstEnums)
	}
	if options.RemoveComments != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("removeComments"), options.RemoveComments)
	}
	if options.RewriteRelativeImportExtensions != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("rewriteRelativeImportExtensions"), options.RewriteRelativeImportExtensions)
	}
	if options.ReactNamespace != "" {
		fn(CommandLineCompilerOptionsMap.Get("reactNamespace"), options.ReactNamespace)
	}
	if options.RootDir != "" {
		fn(CommandLineCompilerOptionsMap.Get("rootDir"), options.RootDir)
	}
	if options.SkipLibCheck != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("skipLibCheck"), options.SkipLibCheck)
	}
	if options.StableTypeOrdering != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("stableTypeOrdering"), options.StableTypeOrdering)
	}
	if options.Strict != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("strict"), options.Strict)
	}
	if options.StrictBindCallApply != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("strictBindCallApply"), options.StrictBindCallApply)
	}
	if options.StrictBuiltinIteratorReturn != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("strictBuiltinIteratorReturn"), options.StrictBuiltinIteratorReturn)
	}
	if options.StrictFunctionTypes != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("strictFunctionTypes"), options.StrictFunctionTypes)
	}
	if options.StrictNullChecks != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("strictNullChecks"), options.StrictNullChecks)
	}
	if options.StrictPropertyInitialization != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("strictPropertyInitialization"), options.StrictPropertyInitialization)
	}
	if options.StripInternal != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("stripInternal"), options.StripInternal)
	}
	if options.SkipDefaultLibCheck != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("skipDefaultLibCheck"), options.SkipDefaultLibCheck)
	}
	if options.SourceMap != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("sourceMap"), options.SourceMap)
	}
	if options.SourceRoot != "" {
		fn(CommandLineCompilerOptionsMap.Get("sourceRoot"), options.SourceRoot)
	}
	if options.Target != 0 {
		fn(CommandLineCompilerOptionsMap.Get("target"), options.Target)
	}
	if options.TsBuildInfoFile != "" {
		fn(CommandLineCompilerOptionsMap.Get("tsBuildInfoFile"), options.TsBuildInfoFile)
	}
	if options.UseDefineForClassFields != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("useDefineForClassFields"), options.UseDefineForClassFields)
	}
	if options.UseUnknownInCatchVariables != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("useUnknownInCatchVariables"), options.UseUnknownInCatchVariables)
	}
	if options.VerbatimModuleSyntax != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("verbatimModuleSyntax"), options.VerbatimModuleSyntax)
	}
	if options.AllowSyntheticDefaultImports != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("allowSyntheticDefaultImports"), options.AllowSyntheticDefaultImports)
	}
	if options.AlwaysStrict != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("alwaysStrict"), options.AlwaysStrict)
	}
	if options.DownlevelIteration != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("downlevelIteration"), options.DownlevelIteration)
	}
	if options.ESModuleInterop != core.TSUnknown {
		fn(CommandLineCompilerOptionsMap.Get("esModuleInterop"), options.ESModuleInterop)
	}
	if options.OutFile != "" {
		fn(CommandLineCompilerOptionsMap.Get("outFile"), options.OutFile)
	}
}
