// Code generated by tools/scripts/tsc/generate-options.ts. DO NOT EDIT.

package tsoptions

import (
	"github.com/microsoft/TypeScript/tsc/internal/collections"
	"github.com/microsoft/TypeScript/tsc/internal/core"
	"github.com/microsoft/TypeScript/tsc/internal/tspath"
)

func parseCompilerOptions(key string, value any, allOptions *core.CompilerOptions) (foundKey bool) {
	if option := CommandLineCompilerOptionsMap.Get(key); option != nil {
		key = option.Name
	}
	switch key {
	case "allowJs":
		allOptions.AllowJs = ParseTristate(value)
	case "allowArbitraryExtensions":
		allOptions.AllowArbitraryExtensions = ParseTristate(value)
	case "allowImportingTsExtensions":
		allOptions.AllowImportingTsExtensions = ParseTristate(value)
	case "allowNonTsExtensions":
		allOptions.AllowNonTsExtensions = ParseTristate(value)
	case "allowUmdGlobalAccess":
		allOptions.AllowUmdGlobalAccess = ParseTristate(value)
	case "allowUnreachableCode":
		allOptions.AllowUnreachableCode = ParseTristate(value)
	case "allowUnusedLabels":
		allOptions.AllowUnusedLabels = ParseTristate(value)
	case "assumeChangesOnlyAffectDirectDependencies":
		allOptions.AssumeChangesOnlyAffectDirectDependencies = ParseTristate(value)
	case "checkJs":
		allOptions.CheckJs = ParseTristate(value)
	case "customConditions":
		allOptions.CustomConditions = ParseStringArray(value)
	case "composite":
		allOptions.Composite = ParseTristate(value)
	case "emitDeclarationOnly":
		allOptions.EmitDeclarationOnly = ParseTristate(value)
	case "emitBOM":
		allOptions.EmitBOM = ParseTristate(value)
	case "emitDecoratorMetadata":
		allOptions.EmitDecoratorMetadata = ParseTristate(value)
	case "declaration":
		allOptions.Declaration = ParseTristate(value)
	case "declarationDir":
		allOptions.DeclarationDir = ParseString(value)
	case "declarationMap":
		allOptions.DeclarationMap = ParseTristate(value)
	case "deduplicatePackages":
		allOptions.DeduplicatePackages = ParseTristate(value)
	case "disableSizeLimit":
		allOptions.DisableSizeLimit = ParseTristate(value)
	case "disableSourceOfProjectReferenceRedirect":
		allOptions.DisableSourceOfProjectReferenceRedirect = ParseTristate(value)
	case "disableSolutionSearching":
		allOptions.DisableSolutionSearching = ParseTristate(value)
	case "disableReferencedProjectLoad":
		allOptions.DisableReferencedProjectLoad = ParseTristate(value)
	case "erasableSyntaxOnly":
		allOptions.ErasableSyntaxOnly = ParseTristate(value)
	case "exactOptionalPropertyTypes":
		allOptions.ExactOptionalPropertyTypes = ParseTristate(value)
	case "experimentalDecorators":
		allOptions.ExperimentalDecorators = ParseTristate(value)
	case "forceConsistentCasingInFileNames":
		allOptions.ForceConsistentCasingInFileNames = ParseTristate(value)
	case "isolatedModules":
		allOptions.IsolatedModules = ParseTristate(value)
	case "isolatedDeclarations":
		allOptions.IsolatedDeclarations = ParseTristate(value)
	case "ignoreConfig":
		allOptions.IgnoreConfig = ParseTristate(value)
	case "ignoreDeprecations":
		allOptions.IgnoreDeprecations = ParseString(value)
	case "importHelpers":
		allOptions.ImportHelpers = ParseTristate(value)
	case "inlineSourceMap":
		allOptions.InlineSourceMap = ParseTristate(value)
	case "inlineSources":
		allOptions.InlineSources = ParseTristate(value)
	case "init":
		allOptions.Init = ParseTristate(value)
	case "incremental":
		allOptions.Incremental = ParseTristate(value)
	case "jsx":
		allOptions.Jsx = floatOrInt32ToFlag[core.JsxEmit](value)
	case "jsxFactory":
		allOptions.JsxFactory = ParseString(value)
	case "jsxFragmentFactory":
		allOptions.JsxFragmentFactory = ParseString(value)
	case "jsxImportSource":
		allOptions.JsxImportSource = ParseString(value)
	case "lib":
		if libs, ok := value.([]string); ok {
			allOptions.Lib = libs
		} else {
			allOptions.Lib = ParseStringArray(value)
		}
	case "libReplacement":
		allOptions.LibReplacement = ParseTristate(value)
	case "locale":
		allOptions.Locale = ParseString(value)
	case "mapRoot":
		allOptions.MapRoot = ParseString(value)
	case "module":
		allOptions.Module = floatOrInt32ToFlag[core.ModuleKind](value)
	case "moduleResolution":
		allOptions.ModuleResolution = floatOrInt32ToFlag[core.ModuleResolutionKind](value)
	case "moduleSuffixes":
		allOptions.ModuleSuffixes = ParseStringArray(value)
	case "moduleDetection", "moduleDetectionKind":
		allOptions.ModuleDetection = floatOrInt32ToFlag[core.ModuleDetectionKind](value)
	case "newLine":
		allOptions.NewLine = floatOrInt32ToFlag[core.NewLineKind](value)
	case "noEmit":
		allOptions.NoEmit = ParseTristate(value)
	case "noCheck":
		allOptions.NoCheck = ParseTristate(value)
	case "noErrorTruncation":
		allOptions.NoErrorTruncation = ParseTristate(value)
	case "noFallthroughCasesInSwitch":
		allOptions.NoFallthroughCasesInSwitch = ParseTristate(value)
	case "noImplicitAny":
		allOptions.NoImplicitAny = ParseTristate(value)
	case "noImplicitThis":
		allOptions.NoImplicitThis = ParseTristate(value)
	case "noImplicitReturns":
		allOptions.NoImplicitReturns = ParseTristate(value)
	case "noEmitHelpers":
		allOptions.NoEmitHelpers = ParseTristate(value)
	case "noLib":
		allOptions.NoLib = ParseTristate(value)
	case "noPropertyAccessFromIndexSignature":
		allOptions.NoPropertyAccessFromIndexSignature = ParseTristate(value)
	case "noUncheckedIndexedAccess":
		allOptions.NoUncheckedIndexedAccess = ParseTristate(value)
	case "noEmitOnError":
		allOptions.NoEmitOnError = ParseTristate(value)
	case "noUnusedLocals":
		allOptions.NoUnusedLocals = ParseTristate(value)
	case "noUnusedParameters":
		allOptions.NoUnusedParameters = ParseTristate(value)
	case "noResolve":
		allOptions.NoResolve = ParseTristate(value)
	case "noImplicitOverride":
		allOptions.NoImplicitOverride = ParseTristate(value)
	case "noUncheckedSideEffectImports":
		allOptions.NoUncheckedSideEffectImports = ParseTristate(value)
	case "outDir":
		allOptions.OutDir = ParseString(value)
	case "paths":
		allOptions.Paths = parseStringMap(value)
	case "plugins":
		if plugins, ok := value.([]any); ok {
			allOptions.Plugins = core.Map(plugins, func(plugin any) core.PluginImport {
				if pluginMap, isMap := plugin.(*collections.OrderedMap[string, any]); isMap {
					return core.PluginImport{Name: ParseString(pluginMap.GetOrZero("name"))}
				}
				return core.PluginImport{}
			})
		}
	case "preserveConstEnums":
		allOptions.PreserveConstEnums = ParseTristate(value)
	case "preserveSymlinks":
		allOptions.PreserveSymlinks = ParseTristate(value)
	case "project":
		allOptions.Project = ParseString(value)
	case "resolveJsonModule":
		allOptions.ResolveJsonModule = ParseTristate(value)
	case "resolvePackageJsonExports":
		allOptions.ResolvePackageJsonExports = ParseTristate(value)
	case "resolvePackageJsonImports":
		allOptions.ResolvePackageJsonImports = ParseTristate(value)
	case "removeComments":
		allOptions.RemoveComments = ParseTristate(value)
	case "rewriteRelativeImportExtensions":
		allOptions.RewriteRelativeImportExtensions = ParseTristate(value)
	case "reactNamespace":
		allOptions.ReactNamespace = ParseString(value)
	case "rootDir":
		allOptions.RootDir = ParseString(value)
	case "rootDirs":
		allOptions.RootDirs = ParseStringArray(value)
	case "skipLibCheck":
		allOptions.SkipLibCheck = ParseTristate(value)
	case "stableTypeOrdering":
		allOptions.StableTypeOrdering = ParseTristate(value)
	case "strict":
		allOptions.Strict = ParseTristate(value)
	case "strictBindCallApply":
		allOptions.StrictBindCallApply = ParseTristate(value)
	case "strictBuiltinIteratorReturn":
		allOptions.StrictBuiltinIteratorReturn = ParseTristate(value)
	case "strictFunctionTypes":
		allOptions.StrictFunctionTypes = ParseTristate(value)
	case "strictNullChecks":
		allOptions.StrictNullChecks = ParseTristate(value)
	case "strictPropertyInitialization":
		allOptions.StrictPropertyInitialization = ParseTristate(value)
	case "stripInternal":
		allOptions.StripInternal = ParseTristate(value)
	case "skipDefaultLibCheck":
		allOptions.SkipDefaultLibCheck = ParseTristate(value)
	case "sourceMap":
		allOptions.SourceMap = ParseTristate(value)
	case "sourceRoot":
		allOptions.SourceRoot = ParseString(value)
	case "suppressOutputPathCheck":
		allOptions.SuppressOutputPathCheck = ParseTristate(value)
	case "target":
		allOptions.Target = floatOrInt32ToFlag[core.ScriptTarget](value)
	case "traceResolution":
		allOptions.TraceResolution = ParseTristate(value)
	case "tsBuildInfoFile":
		allOptions.TsBuildInfoFile = ParseString(value)
	case "typeRoots":
		allOptions.TypeRoots = ParseStringArray(value)
	case "types":
		allOptions.Types = ParseStringArray(value)
	case "useDefineForClassFields":
		allOptions.UseDefineForClassFields = ParseTristate(value)
	case "useUnknownInCatchVariables":
		allOptions.UseUnknownInCatchVariables = ParseTristate(value)
	case "verbatimModuleSyntax":
		allOptions.VerbatimModuleSyntax = ParseTristate(value)
	case "maxNodeModuleJsDepth":
		allOptions.MaxNodeModuleJsDepth = parseNumber(value)
	case "allowSyntheticDefaultImports":
		allOptions.AllowSyntheticDefaultImports = ParseTristate(value)
	case "alwaysStrict":
		allOptions.AlwaysStrict = ParseTristate(value)
	case "baseUrl":
		allOptions.BaseUrl = ParseString(value)
	case "downlevelIteration":
		allOptions.DownlevelIteration = ParseTristate(value)
	case "esModuleInterop":
		allOptions.ESModuleInterop = ParseTristate(value)
	case "outFile":
		allOptions.OutFile = ParseString(value)
	case "configFilePath":
		allOptions.ConfigFilePath = ParseString(value)
	case "noDtsResolution":
		allOptions.NoDtsResolution = ParseTristate(value)
	case "pathsBasePath":
		allOptions.PathsBasePath = ParseString(value)
	case "diagnostics":
		allOptions.Diagnostics = ParseTristate(value)
	case "extendedDiagnostics":
		allOptions.ExtendedDiagnostics = ParseTristate(value)
	case "generateCpuProfile":
		allOptions.GenerateCpuProfile = ParseString(value)
	case "generateTrace":
		allOptions.GenerateTrace = ParseString(value)
	case "listEmittedFiles":
		allOptions.ListEmittedFiles = ParseTristate(value)
	case "listFiles":
		allOptions.ListFiles = ParseTristate(value)
	case "explainFiles":
		allOptions.ExplainFiles = ParseTristate(value)
	case "listFilesOnly":
		allOptions.ListFilesOnly = ParseTristate(value)
	case "noEmitForJsFiles":
		allOptions.NoEmitForJsFiles = ParseTristate(value)
	case "preserveWatchOutput":
		allOptions.PreserveWatchOutput = ParseTristate(value)
	case "pretty":
		allOptions.Pretty = ParseTristate(value)
	case "version":
		allOptions.Version = ParseTristate(value)
	case "watch":
		allOptions.Watch = ParseTristate(value)
	case "showConfig":
		allOptions.ShowConfig = ParseTristate(value)
	case "build":
		allOptions.Build = ParseTristate(value)
	case "help":
		allOptions.Help = ParseTristate(value)
	case "all":
		allOptions.All = ParseTristate(value)
	case "runExternalCode":
		allOptions.RunExternalCode = ParseTristate(value)
	case "pprofDir":
		allOptions.PprofDir = ParseString(value)
	case "singleThreaded":
		allOptions.SingleThreaded = ParseTristate(value)
	case "quiet":
		allOptions.Quiet = ParseTristate(value)
	case "checkers":
		allOptions.Checkers = parseNumber(value)
	default:
		return false
	}
	return true
}

func getDefaultCompilerOptions(configFileName string) *core.CompilerOptions {
	if configFileName != "" && tspath.GetBaseFileName(configFileName) == "jsconfig.json" {
		return &core.CompilerOptions{
			AllowJs:              core.TSTrue,
			NoEmit:               core.TSTrue,
			SkipLibCheck:         core.TSTrue,
			MaxNodeModuleJsDepth: new(2),
		}
	}
	return &core.CompilerOptions{}
}

func getDefaultTypeAcquisition(configFileName string) *core.TypeAcquisition {
	if configFileName != "" && tspath.GetBaseFileName(configFileName) == "jsconfig.json" {
		return &core.TypeAcquisition{
			Enable: core.TSTrue,
		}
	}
	return &core.TypeAcquisition{}
}
