// Code generated by tools/scripts/tsc/generate-options.ts. DO NOT EDIT.

package core

import "github.com/microsoft/TypeScript/tsc/internal/collections"

// CompilerOptions contains the compiler options exposed by the API.
type CompilerOptions struct {
	_                                         noCopy
	AllowJs                                   Tristate                                  `json:"allowJs,omitzero"`
	AllowArbitraryExtensions                  Tristate                                  `json:"allowArbitraryExtensions,omitzero"`
	AllowImportingTsExtensions                Tristate                                  `json:"allowImportingTsExtensions,omitzero"`
	AllowNonTsExtensions                      Tristate                                  `json:"allowNonTsExtensions,omitzero"`
	AllowUmdGlobalAccess                      Tristate                                  `json:"allowUmdGlobalAccess,omitzero"`
	AllowUnreachableCode                      Tristate                                  `json:"allowUnreachableCode,omitzero"`
	AllowUnusedLabels                         Tristate                                  `json:"allowUnusedLabels,omitzero"`
	AssumeChangesOnlyAffectDirectDependencies Tristate                                  `json:"assumeChangesOnlyAffectDirectDependencies,omitzero"`
	CheckJs                                   Tristate                                  `json:"checkJs,omitzero"`
	CustomConditions                          []string                                  `json:"customConditions,omitzero"`
	Composite                                 Tristate                                  `json:"composite,omitzero"`
	EmitDeclarationOnly                       Tristate                                  `json:"emitDeclarationOnly,omitzero"`
	EmitBOM                                   Tristate                                  `json:"emitBOM,omitzero"`
	EmitDecoratorMetadata                     Tristate                                  `json:"emitDecoratorMetadata,omitzero"`
	Declaration                               Tristate                                  `json:"declaration,omitzero"`
	DeclarationDir                            string                                    `json:"declarationDir,omitzero"`
	DeclarationMap                            Tristate                                  `json:"declarationMap,omitzero"`
	DeduplicatePackages                       Tristate                                  `json:"deduplicatePackages,omitzero"`
	DisableSizeLimit                          Tristate                                  `json:"disableSizeLimit,omitzero"`
	DisableSourceOfProjectReferenceRedirect   Tristate                                  `json:"disableSourceOfProjectReferenceRedirect,omitzero"`
	DisableSolutionSearching                  Tristate                                  `json:"disableSolutionSearching,omitzero"`
	DisableReferencedProjectLoad              Tristate                                  `json:"disableReferencedProjectLoad,omitzero"`
	ErasableSyntaxOnly                        Tristate                                  `json:"erasableSyntaxOnly,omitzero"`
	ExactOptionalPropertyTypes                Tristate                                  `json:"exactOptionalPropertyTypes,omitzero"`
	ExperimentalDecorators                    Tristate                                  `json:"experimentalDecorators,omitzero"`
	ForceConsistentCasingInFileNames          Tristate                                  `json:"forceConsistentCasingInFileNames,omitzero"`
	IsolatedModules                           Tristate                                  `json:"isolatedModules,omitzero"`
	IsolatedDeclarations                      Tristate                                  `json:"isolatedDeclarations,omitzero"`
	IgnoreConfig                              Tristate                                  `json:"ignoreConfig,omitzero"`
	IgnoreDeprecations                        string                                    `json:"ignoreDeprecations,omitzero"`
	ImportHelpers                             Tristate                                  `json:"importHelpers,omitzero"`
	InlineSourceMap                           Tristate                                  `json:"inlineSourceMap,omitzero"`
	InlineSources                             Tristate                                  `json:"inlineSources,omitzero"`
	Init                                      Tristate                                  `json:"init,omitzero"`
	Incremental                               Tristate                                  `json:"incremental,omitzero"`
	Jsx                                       JsxEmit                                   `json:"jsx,omitzero"`
	JsxFactory                                string                                    `json:"jsxFactory,omitzero"`
	JsxFragmentFactory                        string                                    `json:"jsxFragmentFactory,omitzero"`
	JsxImportSource                           string                                    `json:"jsxImportSource,omitzero"`
	Lib                                       []string                                  `json:"lib,omitzero"`
	LibReplacement                            Tristate                                  `json:"libReplacement,omitzero"`
	Locale                                    string                                    `json:"locale,omitzero"`
	MapRoot                                   string                                    `json:"mapRoot,omitzero"`
	Module                                    ModuleKind                                `json:"module,omitzero"`
	ModuleResolution                          ModuleResolutionKind                      `json:"moduleResolution,omitzero"`
	ModuleSuffixes                            []string                                  `json:"moduleSuffixes,omitzero"`
	ModuleDetection                           ModuleDetectionKind                       `json:"moduleDetection,omitzero"`
	NewLine                                   NewLineKind                               `json:"newLine,omitzero"`
	NoEmit                                    Tristate                                  `json:"noEmit,omitzero"`
	NoCheck                                   Tristate                                  `json:"noCheck,omitzero"`
	NoErrorTruncation                         Tristate                                  `json:"noErrorTruncation,omitzero"`
	NoFallthroughCasesInSwitch                Tristate                                  `json:"noFallthroughCasesInSwitch,omitzero"`
	NoImplicitAny                             Tristate                                  `json:"noImplicitAny,omitzero"`
	NoImplicitThis                            Tristate                                  `json:"noImplicitThis,omitzero"`
	NoImplicitReturns                         Tristate                                  `json:"noImplicitReturns,omitzero"`
	NoEmitHelpers                             Tristate                                  `json:"noEmitHelpers,omitzero"`
	NoLib                                     Tristate                                  `json:"noLib,omitzero"`
	NoPropertyAccessFromIndexSignature        Tristate                                  `json:"noPropertyAccessFromIndexSignature,omitzero"`
	NoUncheckedIndexedAccess                  Tristate                                  `json:"noUncheckedIndexedAccess,omitzero"`
	NoEmitOnError                             Tristate                                  `json:"noEmitOnError,omitzero"`
	NoUnusedLocals                            Tristate                                  `json:"noUnusedLocals,omitzero"`
	NoUnusedParameters                        Tristate                                  `json:"noUnusedParameters,omitzero"`
	NoResolve                                 Tristate                                  `json:"noResolve,omitzero"`
	NoImplicitOverride                        Tristate                                  `json:"noImplicitOverride,omitzero"`
	NoUncheckedSideEffectImports              Tristate                                  `json:"noUncheckedSideEffectImports,omitzero"`
	OutDir                                    string                                    `json:"outDir,omitzero"`
	Paths                                     *collections.OrderedMap[string, []string] `json:"paths,omitzero"`
	// Plugins are parsed only so tools can report that native TypeScript does not support them.
	Plugins                         []PluginImport `json:"plugins,omitzero"`
	PreserveConstEnums              Tristate       `json:"preserveConstEnums,omitzero"`
	PreserveSymlinks                Tristate       `json:"preserveSymlinks,omitzero"`
	Project                         string         `json:"project,omitzero"`
	ResolveJsonModule               Tristate       `json:"resolveJsonModule,omitzero"`
	ResolvePackageJsonExports       Tristate       `json:"resolvePackageJsonExports,omitzero"`
	ResolvePackageJsonImports       Tristate       `json:"resolvePackageJsonImports,omitzero"`
	RemoveComments                  Tristate       `json:"removeComments,omitzero"`
	RewriteRelativeImportExtensions Tristate       `json:"rewriteRelativeImportExtensions,omitzero"`
	ReactNamespace                  string         `json:"reactNamespace,omitzero"`
	RootDir                         string         `json:"rootDir,omitzero"`
	RootDirs                        []string       `json:"rootDirs,omitzero"`
	SkipLibCheck                    Tristate       `json:"skipLibCheck,omitzero"`
	StableTypeOrdering              Tristate       `json:"stableTypeOrdering,omitzero"`
	Strict                          Tristate       `json:"strict,omitzero"`
	StrictBindCallApply             Tristate       `json:"strictBindCallApply,omitzero"`
	StrictBuiltinIteratorReturn     Tristate       `json:"strictBuiltinIteratorReturn,omitzero"`
	StrictFunctionTypes             Tristate       `json:"strictFunctionTypes,omitzero"`
	StrictNullChecks                Tristate       `json:"strictNullChecks,omitzero"`
	StrictPropertyInitialization    Tristate       `json:"strictPropertyInitialization,omitzero"`
	StripInternal                   Tristate       `json:"stripInternal,omitzero"`
	SkipDefaultLibCheck             Tristate       `json:"skipDefaultLibCheck,omitzero"`
	SourceMap                       Tristate       `json:"sourceMap,omitzero"`
	SourceRoot                      string         `json:"sourceRoot,omitzero"`
	SuppressOutputPathCheck         Tristate       `json:"suppressOutputPathCheck,omitzero"`
	Target                          ScriptTarget   `json:"target,omitzero"`
	TraceResolution                 Tristate       `json:"traceResolution,omitzero"`
	TsBuildInfoFile                 string         `json:"tsBuildInfoFile,omitzero"`
	TypeRoots                       []string       `json:"typeRoots,omitzero"`
	Types                           []string       `json:"types,omitzero"`
	UseDefineForClassFields         Tristate       `json:"useDefineForClassFields,omitzero"`
	UseUnknownInCatchVariables      Tristate       `json:"useUnknownInCatchVariables,omitzero"`
	VerbatimModuleSyntax            Tristate       `json:"verbatimModuleSyntax,omitzero"`
	MaxNodeModuleJsDepth            *int           `json:"maxNodeModuleJsDepth,omitzero"`
	// Deprecated: Do not use outside of options parsing and validation.
	AllowSyntheticDefaultImports Tristate `json:"allowSyntheticDefaultImports,omitzero" deprecated:"true"`
	// Deprecated: Do not use outside of options parsing and validation.
	AlwaysStrict Tristate `json:"alwaysStrict,omitzero" deprecated:"true"`
	// Deprecated: Do not use outside of options parsing and validation.
	BaseUrl string `json:"baseUrl,omitzero" deprecated:"true"`
	// Deprecated: Do not use outside of options parsing and validation.
	DownlevelIteration Tristate `json:"downlevelIteration,omitzero" deprecated:"true"`
	// Deprecated: Do not use outside of options parsing and validation.
	ESModuleInterop Tristate `json:"esModuleInterop,omitzero" deprecated:"true"`
	// Deprecated: Do not use outside of options parsing and validation.
	OutFile string `json:"outFile,omitzero" deprecated:"true"`
	// Internal fields
	ConfigFilePath      string   `json:"configFilePath,omitzero"`
	NoDtsResolution     Tristate `json:"noDtsResolution,omitzero" internal:"true"`
	PathsBasePath       string   `json:"pathsBasePath,omitzero" internal:"true"`
	Diagnostics         Tristate `json:"diagnostics,omitzero" internal:"true"`
	ExtendedDiagnostics Tristate `json:"extendedDiagnostics,omitzero" internal:"true"`
	GenerateCpuProfile  string   `json:"generateCpuProfile,omitzero" internal:"true"`
	GenerateTrace       string   `json:"generateTrace,omitzero" internal:"true"`
	ListEmittedFiles    Tristate `json:"listEmittedFiles,omitzero" internal:"true"`
	ListFiles           Tristate `json:"listFiles,omitzero" internal:"true"`
	ExplainFiles        Tristate `json:"explainFiles,omitzero" internal:"true"`
	ListFilesOnly       Tristate `json:"listFilesOnly,omitzero" internal:"true"`
	NoEmitForJsFiles    Tristate `json:"noEmitForJsFiles,omitzero" internal:"true"`
	PreserveWatchOutput Tristate `json:"preserveWatchOutput,omitzero" internal:"true"`
	Pretty              Tristate `json:"pretty,omitzero" internal:"true"`
	Version             Tristate `json:"version,omitzero" internal:"true"`
	Watch               Tristate `json:"watch,omitzero" internal:"true"`
	ShowConfig          Tristate `json:"showConfig,omitzero" internal:"true"`
	Build               Tristate `json:"build,omitzero" internal:"true"`
	Help                Tristate `json:"help,omitzero" internal:"true"`
	All                 Tristate `json:"all,omitzero" internal:"true"`
	RunExternalCode     Tristate `json:"runExternalCode,omitzero" internal:"true"`
	PprofDir            string   `json:"pprofDir,omitzero" internal:"true"`
	SingleThreaded      Tristate `json:"singleThreaded,omitzero" internal:"true"`
	Quiet               Tristate `json:"quiet,omitzero" internal:"true"`
	Checkers            *int     `json:"checkers,omitzero" internal:"true"`
}

// Clone creates a shallow copy of the CompilerOptions.
func (options *CompilerOptions) Clone() *CompilerOptions {
	return &CompilerOptions{
		AllowJs:                                   options.AllowJs,
		AllowArbitraryExtensions:                  options.AllowArbitraryExtensions,
		AllowImportingTsExtensions:                options.AllowImportingTsExtensions,
		AllowNonTsExtensions:                      options.AllowNonTsExtensions,
		AllowUmdGlobalAccess:                      options.AllowUmdGlobalAccess,
		AllowUnreachableCode:                      options.AllowUnreachableCode,
		AllowUnusedLabels:                         options.AllowUnusedLabels,
		AssumeChangesOnlyAffectDirectDependencies: options.AssumeChangesOnlyAffectDirectDependencies,
		CheckJs:                                 options.CheckJs,
		CustomConditions:                        options.CustomConditions,
		Composite:                               options.Composite,
		EmitDeclarationOnly:                     options.EmitDeclarationOnly,
		EmitBOM:                                 options.EmitBOM,
		EmitDecoratorMetadata:                   options.EmitDecoratorMetadata,
		Declaration:                             options.Declaration,
		DeclarationDir:                          options.DeclarationDir,
		DeclarationMap:                          options.DeclarationMap,
		DeduplicatePackages:                     options.DeduplicatePackages,
		DisableSizeLimit:                        options.DisableSizeLimit,
		DisableSourceOfProjectReferenceRedirect: options.DisableSourceOfProjectReferenceRedirect,
		DisableSolutionSearching:                options.DisableSolutionSearching,
		DisableReferencedProjectLoad:            options.DisableReferencedProjectLoad,
		ErasableSyntaxOnly:                      options.ErasableSyntaxOnly,
		ExactOptionalPropertyTypes:              options.ExactOptionalPropertyTypes,
		ExperimentalDecorators:                  options.ExperimentalDecorators,
		ForceConsistentCasingInFileNames:        options.ForceConsistentCasingInFileNames,
		IsolatedModules:                         options.IsolatedModules,
		IsolatedDeclarations:                    options.IsolatedDeclarations,
		IgnoreConfig:                            options.IgnoreConfig,
		IgnoreDeprecations:                      options.IgnoreDeprecations,
		ImportHelpers:                           options.ImportHelpers,
		InlineSourceMap:                         options.InlineSourceMap,
		InlineSources:                           options.InlineSources,
		Init:                                    options.Init,
		Incremental:                             options.Incremental,
		Jsx:                                     options.Jsx,
		JsxFactory:                              options.JsxFactory,
		JsxFragmentFactory:                      options.JsxFragmentFactory,
		JsxImportSource:                         options.JsxImportSource,
		Lib:                                     options.Lib,
		LibReplacement:                          options.LibReplacement,
		Locale:                                  options.Locale,
		MapRoot:                                 options.MapRoot,
		Module:                                  options.Module,
		ModuleResolution:                        options.ModuleResolution,
		ModuleSuffixes:                          options.ModuleSuffixes,
		ModuleDetection:                         options.ModuleDetection,
		NewLine:                                 options.NewLine,
		NoEmit:                                  options.NoEmit,
		NoCheck:                                 options.NoCheck,
		NoErrorTruncation:                       options.NoErrorTruncation,
		NoFallthroughCasesInSwitch:              options.NoFallthroughCasesInSwitch,
		NoImplicitAny:                           options.NoImplicitAny,
		NoImplicitThis:                          options.NoImplicitThis,
		NoImplicitReturns:                       options.NoImplicitReturns,
		NoEmitHelpers:                           options.NoEmitHelpers,
		NoLib:                                   options.NoLib,
		NoPropertyAccessFromIndexSignature:      options.NoPropertyAccessFromIndexSignature,
		NoUncheckedIndexedAccess:                options.NoUncheckedIndexedAccess,
		NoEmitOnError:                           options.NoEmitOnError,
		NoUnusedLocals:                          options.NoUnusedLocals,
		NoUnusedParameters:                      options.NoUnusedParameters,
		NoResolve:                               options.NoResolve,
		NoImplicitOverride:                      options.NoImplicitOverride,
		NoUncheckedSideEffectImports:            options.NoUncheckedSideEffectImports,
		OutDir:                                  options.OutDir,
		Paths:                                   options.Paths,
		Plugins:                                 options.Plugins,
		PreserveConstEnums:                      options.PreserveConstEnums,
		PreserveSymlinks:                        options.PreserveSymlinks,
		Project:                                 options.Project,
		ResolveJsonModule:                       options.ResolveJsonModule,
		ResolvePackageJsonExports:               options.ResolvePackageJsonExports,
		ResolvePackageJsonImports:               options.ResolvePackageJsonImports,
		RemoveComments:                          options.RemoveComments,
		RewriteRelativeImportExtensions:         options.RewriteRelativeImportExtensions,
		ReactNamespace:                          options.ReactNamespace,
		RootDir:                                 options.RootDir,
		RootDirs:                                options.RootDirs,
		SkipLibCheck:                            options.SkipLibCheck,
		StableTypeOrdering:                      options.StableTypeOrdering,
		Strict:                                  options.Strict,
		StrictBindCallApply:                     options.StrictBindCallApply,
		StrictBuiltinIteratorReturn:             options.StrictBuiltinIteratorReturn,
		StrictFunctionTypes:                     options.StrictFunctionTypes,
		StrictNullChecks:                        options.StrictNullChecks,
		StrictPropertyInitialization:            options.StrictPropertyInitialization,
		StripInternal:                           options.StripInternal,
		SkipDefaultLibCheck:                     options.SkipDefaultLibCheck,
		SourceMap:                               options.SourceMap,
		SourceRoot:                              options.SourceRoot,
		SuppressOutputPathCheck:                 options.SuppressOutputPathCheck,
		Target:                                  options.Target,
		TraceResolution:                         options.TraceResolution,
		TsBuildInfoFile:                         options.TsBuildInfoFile,
		TypeRoots:                               options.TypeRoots,
		Types:                                   options.Types,
		UseDefineForClassFields:                 options.UseDefineForClassFields,
		UseUnknownInCatchVariables:              options.UseUnknownInCatchVariables,
		VerbatimModuleSyntax:                    options.VerbatimModuleSyntax,
		MaxNodeModuleJsDepth:                    options.MaxNodeModuleJsDepth,
		AllowSyntheticDefaultImports:            options.AllowSyntheticDefaultImports,
		AlwaysStrict:                            options.AlwaysStrict,
		BaseUrl:                                 options.BaseUrl,
		DownlevelIteration:                      options.DownlevelIteration,
		ESModuleInterop:                         options.ESModuleInterop,
		OutFile:                                 options.OutFile,
		ConfigFilePath:                          options.ConfigFilePath,
		NoDtsResolution:                         options.NoDtsResolution,
		PathsBasePath:                           options.PathsBasePath,
		Diagnostics:                             options.Diagnostics,
		ExtendedDiagnostics:                     options.ExtendedDiagnostics,
		GenerateCpuProfile:                      options.GenerateCpuProfile,
		GenerateTrace:                           options.GenerateTrace,
		ListEmittedFiles:                        options.ListEmittedFiles,
		ListFiles:                               options.ListFiles,
		ExplainFiles:                            options.ExplainFiles,
		ListFilesOnly:                           options.ListFilesOnly,
		NoEmitForJsFiles:                        options.NoEmitForJsFiles,
		PreserveWatchOutput:                     options.PreserveWatchOutput,
		Pretty:                                  options.Pretty,
		Version:                                 options.Version,
		Watch:                                   options.Watch,
		ShowConfig:                              options.ShowConfig,
		Build:                                   options.Build,
		Help:                                    options.Help,
		All:                                     options.All,
		RunExternalCode:                         options.RunExternalCode,
		PprofDir:                                options.PprofDir,
		SingleThreaded:                          options.SingleThreaded,
		Quiet:                                   options.Quiet,
		Checkers:                                options.Checkers,
	}
}
