// Code generated by "stringer -type=LanguageVariant -output=languagevariant_stringer_generated.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LanguageVariantStandard-0]
	_ = x[LanguageVariantJSX-1]
}

const _LanguageVariant_name = "LanguageVariantStandardLanguageVariantJSX"

var _LanguageVariant_index = [...]uint8{0, 23, 41}

func (i LanguageVariant) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LanguageVariant_index)-1 {
		return "LanguageVariant(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LanguageVariant_name[_LanguageVariant_index[idx]:_LanguageVariant_index[idx+1]]
}
