// Code generated by tools/scripts/tsc/generate-options.ts. DO NOT EDIT.

package core

//go:generate npx hereby generate:compileroptions

type ModuleDetectionKind int32

const (
	ModuleDetectionKindNone   ModuleDetectionKind = 0
	ModuleDetectionKindAuto   ModuleDetectionKind = 1
	ModuleDetectionKindLegacy ModuleDetectionKind = 2
	ModuleDetectionKindForce  ModuleDetectionKind = 3
)

type ModuleKind int32

const (
	ModuleKindNone     ModuleKind = 0
	ModuleKindCommonJS ModuleKind = 1
	// Deprecated: Do not use outside of options parsing and validation.
	ModuleKindAMD ModuleKind = 2
	// Deprecated: Do not use outside of options parsing and validation.
	ModuleKindUMD ModuleKind = 3
	// Deprecated: Do not use outside of options parsing and validation.
	ModuleKindSystem ModuleKind = 4
	// NOTE: ES module kinds should be contiguous to more easily check whether a module kind is *any* ES module kind.
	// Non-ES module kinds should not come between ES2015 (the earliest ES module kind) and ESNext (the last ES
	// module kind).
	ModuleKindES2015 ModuleKind = 5
	ModuleKindES2020 ModuleKind = 6
	ModuleKindES2022 ModuleKind = 7
	ModuleKindESNext ModuleKind = 99
	// Node16+ is an amalgam of commonjs (albeit updated) and es2022+, and represents a distinct module system from es2020/esnext
	ModuleKindNode16   ModuleKind = 100
	ModuleKindNode18   ModuleKind = 101
	ModuleKindNode20   ModuleKind = 102
	ModuleKindNodeNext ModuleKind = 199
	// Emit as written
	ModuleKindPreserve ModuleKind = 200
)

type ModuleResolutionKind int32

const (
	ModuleResolutionKindUnknown ModuleResolutionKind = 0
	// Deprecated: Do not use outside of options parsing and validation.
	ModuleResolutionKindClassic ModuleResolutionKind = 1
	// Deprecated: Do not use outside of options parsing and validation.
	ModuleResolutionKindNode10 ModuleResolutionKind = 2
	// Starting with node16, node's module resolver has significant departures from traditional cjs resolution
	// to better support ECMAScript modules and their use within node - however more features are still being added.
	// TypeScript's Node ESM support was introduced after Node 12 went end-of-life, and Node 14 is the earliest stable
	// version that supports both pattern trailers - *but*, Node 16 is the first version that also supports ECMAScript 2022.
	// In turn, we offer both a `NodeNext` moving resolution target, and a `Node16` version-anchored resolution target
	ModuleResolutionKindNode16   ModuleResolutionKind = 3
	ModuleResolutionKindNodeNext ModuleResolutionKind = 99 // Not simply `Node16` so that compiled code linked against TS can use the `Next` value reliably (same as with `ModuleKind`)
	ModuleResolutionKindBundler  ModuleResolutionKind = 100
)

type NewLineKind int32

const (
	NewLineKindNone NewLineKind = 0
	NewLineKindCRLF NewLineKind = 1
	NewLineKindLF   NewLineKind = 2
)

type ScriptTarget int32

const (
	ScriptTargetNone ScriptTarget = 0
	// Deprecated: Do not use outside of options parsing and validation.
	ScriptTargetES5            ScriptTarget = 1
	ScriptTargetES2015         ScriptTarget = 2
	ScriptTargetES2016         ScriptTarget = 3
	ScriptTargetES2017         ScriptTarget = 4
	ScriptTargetES2018         ScriptTarget = 5
	ScriptTargetES2019         ScriptTarget = 6
	ScriptTargetES2020         ScriptTarget = 7
	ScriptTargetES2021         ScriptTarget = 8
	ScriptTargetES2022         ScriptTarget = 9
	ScriptTargetES2023         ScriptTarget = 10
	ScriptTargetES2024         ScriptTarget = 11
	ScriptTargetES2025         ScriptTarget = 12
	ScriptTargetESNext         ScriptTarget = 99
	ScriptTargetJSON           ScriptTarget = 100
	ScriptTargetLatest         ScriptTarget = ScriptTargetESNext
	ScriptTargetLatestStandard ScriptTarget = ScriptTargetES2025
)

type JsxEmit int32

const (
	JsxEmitNone        JsxEmit = 0
	JsxEmitPreserve    JsxEmit = 1
	JsxEmitReact       JsxEmit = 2
	JsxEmitReactNative JsxEmit = 3
	JsxEmitReactJSX    JsxEmit = 4
	JsxEmitReactJSXDev JsxEmit = 5
)

type WatchFileKind int32

const (
	WatchFileKindNone                         WatchFileKind = 0
	WatchFileKindFixedPollingInterval         WatchFileKind = 1
	WatchFileKindPriorityPollingInterval      WatchFileKind = 2
	WatchFileKindDynamicPriorityPolling       WatchFileKind = 3
	WatchFileKindFixedChunkSizePolling        WatchFileKind = 4
	WatchFileKindUseFsEvents                  WatchFileKind = 5
	WatchFileKindUseFsEventsOnParentDirectory WatchFileKind = 6
)

type WatchDirectoryKind int32

const (
	WatchDirectoryKindNone                   WatchDirectoryKind = 0
	WatchDirectoryKindUseFsEvents            WatchDirectoryKind = 1
	WatchDirectoryKindFixedPollingInterval   WatchDirectoryKind = 2
	WatchDirectoryKindDynamicPriorityPolling WatchDirectoryKind = 3
	WatchDirectoryKindFixedChunkSizePolling  WatchDirectoryKind = 4
)

type PollingKind int32

const (
	PollingKindNone             PollingKind = 0
	PollingKindFixedInterval    PollingKind = 1
	PollingKindPriorityInterval PollingKind = 2
	PollingKindDynamicPriority  PollingKind = 3
	PollingKindFixedChunkSize   PollingKind = 4
)

var ModuleKindToModuleResolutionKind = map[ModuleKind]ModuleResolutionKind{
	ModuleKindNode16:   ModuleResolutionKindNode16,
	ModuleKindNodeNext: ModuleResolutionKindNodeNext,
}
