/* Generated file to emulate the ts namespace. */

export * from "../../compiler/_namespaces/ts";
export * from "../../jsTyping/_namespaces/ts";
export * from "../types";
export * from "../utilities";
export * from "../exportInfoMap";
export * from "../classifier";
export * from "../documentHighlights";
export * from "../documentRegistry";
export * from "../getEditsForFileRename";
export * from "../patternMatcher";
export * from "../preProcess";
export * from "../sourcemaps";
export * from "../suggestionDiagnostics";
export * from "../transpile";
export * from "../services";
export * from "../transform";
import * as BreakpointResolver from "./ts.BreakpointResolver";
export { BreakpointResolver };
import * as CallHierarchy from "./ts.CallHierarchy";
export { CallHierarchy };
import * as classifier from "./ts.classifier";
export { classifier };
import * as codefix from "./ts.codefix";
export { codefix };
import * as Completions from "./ts.Completions";
export { Completions };
import * as FindAllReferences from "./ts.FindAllReferences";
export { FindAllReferences };
import * as GoToDefinition from "./ts.GoToDefinition";
export { GoToDefinition };
import * as InlayHints from "./ts.InlayHints";
export { InlayHints };
import * as JsDoc from "./ts.JsDoc";
export { JsDoc };
import * as NavigateTo from "./ts.NavigateTo";
export { NavigateTo };
import * as NavigationBar from "./ts.NavigationBar";
export { NavigationBar };
import * as OrganizeImports from "./ts.OrganizeImports";
export { OrganizeImports };
import * as OutliningElementsCollector from "./ts.OutliningElementsCollector";
export { OutliningElementsCollector };
import * as refactor from "./ts.refactor";
export { refactor };
import * as Rename from "./ts.Rename";
export { Rename };
import * as SignatureHelp from "./ts.SignatureHelp";
export { SignatureHelp };
import * as SmartSelectionRange from "./ts.SmartSelectionRange";
export { SmartSelectionRange };
import * as SymbolDisplay from "./ts.SymbolDisplay";
export { SymbolDisplay };
import * as textChanges from "./ts.textChanges";
export { textChanges };
import * as formatting from "./ts.formatting";
export { formatting };
