/* Generated file to emulate the ts namespace. */

export * from "../../compiler/_namespaces/ts";
export * from "../../jsTyping/_namespaces/ts";
export * from "../types";
export * from "../utilities";
export * from "../exportInfoMap";
export * from "../classifier";
export * from "../documentHighlights";
export * from "../documentRegistry";
export * from "../getEditsForFileRename";
export * from "../patternMatcher";
export * from "../preProcess";
export * from "../sourcemaps";
export * from "../suggestionDiagnostics";
export * from "../transpile";
export * from "../services";
export * from "../transform";
export * from "../shims";
export * as BreakpointResolver from "./ts.BreakpointResolver";
export * as CallHierarchy from "./ts.CallHierarchy";
export * as classifier from "./ts.classifier";
export * as codefix from "./ts.codefix";
export * as Completions from "./ts.Completions";
export * as FindAllReferences from "./ts.FindAllReferences";
export * as GoToDefinition from "./ts.GoToDefinition";
export * as InlayHints from "./ts.InlayHints";
export * as JsDoc from "./ts.JsDoc";
export * as NavigateTo from "./ts.NavigateTo";
export * as NavigationBar from "./ts.NavigationBar";
export * as OrganizeImports from "./ts.OrganizeImports";
export * as OutliningElementsCollector from "./ts.OutliningElementsCollector";
export * as refactor from "./ts.refactor";
export * as Rename from "./ts.Rename";
export * as SignatureHelp from "./ts.SignatureHelp";
export * as SmartSelectionRange from "./ts.SmartSelectionRange";
export * as SymbolDisplay from "./ts.SymbolDisplay";
export * as textChanges from "./ts.textChanges";
export * as formatting from "./ts.formatting";
