/// <reference path="fourslash.ts" />

//// type GeneratePrefixedNumbers<Limit extends number, Prefix extends string, Result extends number[] = []> = 
////     Result['length'] extends Limit ? `${Prefix}${Result[number]}` : GeneratePrefixedNumbers<Limit, Prefix, [...Result, Result['length']]>;
//// 
//// type PrefixedNumbersUpTo5 = GeneratePrefixedNumbers<5, 'name'>; // result = "name0" | "name1" | "name2" | "name3" | "name4"
//// 
//// interface A<T extends number, U extends string> {
////     foo(bar: GeneratePrefixedNumbers<T, U>): GeneratePrefixedNumbers<T, U>;
////     get bar(): GeneratePrefixedNumbers<T, U>;
////     set bar(value: GeneratePrefixedNumbers<T, U>);
////     baz<V extends GeneratePrefixedNumbers<T,U>>(value: V): V;
//// }
//// 
//// class B implements A<999, 'ASuperLongStringASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueThatWeOnlyWeOnlyUsedToHitTheNoTruncation'> {
//// }

verify.codeFix({
    description: "Implement interface 'A<999, 'ASuperLongStringASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueThatWeOnlyWeOnlyUsedToHitTheNoTruncation'>'",
    newFileContent:
`type GeneratePrefixedNumbers<Limit extends number, Prefix extends string, Result extends number[] = []> = 
    Result['length'] extends Limit ? \`\${Prefix}\${Result[number]}\` : GeneratePrefixedNumbers<Limit, Prefix, [...Result, Result['length']]>;

type PrefixedNumbersUpTo5 = GeneratePrefixedNumbers<5, 'name'>; // result = "name0" | "name1" | "name2" | "name3" | "name4"

interface A<T extends number, U extends string> {
    foo(bar: GeneratePrefixedNumbers<T, U>): GeneratePrefixedNumbers<T, U>;
    get bar(): GeneratePrefixedNumbers<T, U>;
    set bar(value: GeneratePrefixedNumbers<T, U>);
    baz<V extends GeneratePrefixedNumbers<T,U>>(value: V): V;
}

class B implements A<999, 'ASuperLongStringASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueASuperLongStringThatWeOnlyWeOnlyUsedToHitTheNoTruncationIssueThatWeOnlyWeOnlyUsedToHitTheNoTruncation'> {
    foo(bar: /*elided*/ any): /*elided*/ any {
        throw new Error("Method not implemented.");
    }
    get bar(): /*elided*/ any {
        throw new Error("Method not implemented.");
    }
    set bar(value: /*elided*/ any) {
        throw new Error("Method not implemented.");
    }
    baz<V extends /*elided*/ any>(value: V): V {
        throw new Error("Method not implemented.");
    }
}`,
});