/// <reference path="fourslash.ts"/>

/////**/

goTo.marker();
verify.completionListContains("break");
verify.completionListContains("case");
verify.completionListContains("catch");
verify.completionListContains("class");
verify.completionListContains("constructor");
verify.completionListContains("continue");
verify.completionListContains("debugger");
verify.completionListContains("declare");
verify.completionListContains("default");
verify.completionListContains("delete");
verify.completionListContains("do");
verify.completionListContains("else");
verify.completionListContains("enum");
verify.completionListContains("export");
verify.completionListContains("extends");
verify.completionListContains("false");
verify.completionListContains("finally");
verify.completionListContains("for");
verify.completionListContains("function");
verify.completionListContains("get");
verify.completionListContains("if");
verify.completionListContains("implements");
verify.completionListContains("import");
verify.completionListContains("in");
verify.completionListContains("instanceof");
verify.completionListContains("interface");
verify.completionListContains("module");
verify.completionListContains("new");
verify.completionListContains("private");
verify.completionListContains("public");
verify.completionListContains("return");
verify.completionListContains("set");
verify.completionListContains("static");
verify.completionListContains("super");
verify.completionListContains("switch");
verify.completionListContains("this");
verify.completionListContains("throw");
verify.completionListContains("true");
verify.completionListContains("try");
verify.completionListContains("typeof");
verify.completionListContains("var");
verify.completionListContains("while");
verify.completionListContains("with");
