version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ['*']
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /tsc
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /tools
    schedule:
      interval: weekly
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
