export enum ObjectFlags {
    None = 0,
    Class = 1 << 0,
    Interface = 1 << 1,
    Reference = 1 << 2,
    Tuple = 1 << 3,
    Anonymous = 1 << 4,
    Mapped = 1 << 5,
    Instantiated = 1 << 6,
    ObjectLiteral = 1 << 7,
    EvolvingArray = 1 << 8,
    ObjectLiteralPatternWithComputedProperties = 1 << 9,
    ReverseMapped = 1 << 10,
    JsxAttributes = 1 << 11,
    JSLiteral = 1 << 12,
    FreshLiteral = 1 << 13,
    ArrayLiteral = 1 << 14,
    SingleSignatureType = 1 << 27,
    ClassOrInterface = Class | Interface,
    ContainsSpread = 1 << 21,
    ObjectRestType = 1 << 22,
    InstantiationExpressionType = 1 << 23,
}
