export var ObjectFlags: any;
(function (ObjectFlags) {
    ObjectFlags[ObjectFlags["None"] = 0] = "None";
    ObjectFlags[ObjectFlags["Class"] = 1] = "Class";
    ObjectFlags[ObjectFlags["Interface"] = 2] = "Interface";
    ObjectFlags[ObjectFlags["Reference"] = 4] = "Reference";
    ObjectFlags[ObjectFlags["Tuple"] = 8] = "Tuple";
    ObjectFlags[ObjectFlags["Anonymous"] = 16] = "Anonymous";
    ObjectFlags[ObjectFlags["Mapped"] = 32] = "Mapped";
    ObjectFlags[ObjectFlags["Instantiated"] = 64] = "Instantiated";
    ObjectFlags[ObjectFlags["ObjectLiteral"] = 128] = "ObjectLiteral";
    ObjectFlags[ObjectFlags["EvolvingArray"] = 256] = "EvolvingArray";
    ObjectFlags[ObjectFlags["ObjectLiteralPatternWithComputedProperties"] = 512] = "ObjectLiteralPatternWithComputedProperties";
    ObjectFlags[ObjectFlags["ReverseMapped"] = 1024] = "ReverseMapped";
    ObjectFlags[ObjectFlags["JsxAttributes"] = 2048] = "JsxAttributes";
    ObjectFlags[ObjectFlags["JSLiteral"] = 4096] = "JSLiteral";
    ObjectFlags[ObjectFlags["FreshLiteral"] = 8192] = "FreshLiteral";
    ObjectFlags[ObjectFlags["ArrayLiteral"] = 16384] = "ArrayLiteral";
    ObjectFlags[ObjectFlags["SingleSignatureType"] = 134217728] = "SingleSignatureType";
    ObjectFlags[ObjectFlags["ClassOrInterface"] = 3] = "ClassOrInterface";
    ObjectFlags[ObjectFlags["ContainsSpread"] = 2097152] = "ContainsSpread";
    ObjectFlags[ObjectFlags["ObjectRestType"] = 4194304] = "ObjectRestType";
    ObjectFlags[ObjectFlags["InstantiationExpressionType"] = 8388608] = "InstantiationExpressionType";
})(ObjectFlags || (ObjectFlags = {}));
