# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/custom-gcl.jsonschema.json

version: v2.12.2

destination: ./_tools

plugins:
  - module: 'github.com/microsoft/TypeScript/tsc/_tools'
    import: 'github.com/microsoft/TypeScript/tsc/_tools/customlint'
    path: ./_tools
