package pnp

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/microsoft/TypeScript/tsc/internal/json"
	"github.com/microsoft/TypeScript/tsc/internal/repo"
	"github.com/microsoft/TypeScript/tsc/internal/tspath"
	"github.com/microsoft/TypeScript/tsc/internal/vfs/osvfs"
)

type TestSuite struct {
	Manifest json.Value `json:"manifest"`
	Tests    []TestCase `json:"tests"`
}

type TestCase struct {
	Imported string `json:"imported"`
	Importer string `json:"importer"`
	Expected string `json:"expected"`
	It       string `json:"it"`
}

func TestLoadPnPManifest(t *testing.T) {
	t.Parallel()
	cases := []struct {
		fileName string
		path     string
		msg      string
	}{
		{"pnp-yarn-v3.cjs", filepath.Join(repo.TestDataPath(), "fixtures", "pnp", "pnp-yarn-v3.cjs"), "Expected to load the .pnp.cjs file generated by Yarn 3"},
		{"pnp-yarn-v4.cjs", filepath.Join(repo.TestDataPath(), "fixtures", "pnp", "pnp-yarn-v4.cjs"), "Expected to load the .pnp.cjs file generated by Yarn 4"},
	}

	for _, tc := range cases {
		t.Run(tc.path, func(t *testing.T) {
			t.Parallel()

			fs := osvfs.FS()
			pnpDataString, err := extractPnpDataStringFromPath(fs, tc.path)
			if err != nil {
				t.Fatalf("failed to parse manifest: %v", err)
			}
			_, err = parseManifestFromData(pnpDataString, tspath.GetDirectoryPath(tc.path))
			if err != nil {
				t.Fatalf("failed to parse manifest: %v", err)
			}
		})
	}
}

func TestResolveUnqualified(t *testing.T) {
	t.Parallel()
	expectationsPath := filepath.Join(repo.TestDataPath(), "fixtures", "pnp", "test-expectations.json")

	content, err := os.ReadFile(expectationsPath)
	if err != nil {
		t.Fatalf("Assertion failed: Expected the expectations to be found: %v", err)
	}

	var suites []TestSuite
	if err = json.Unmarshal(content, &suites); err != nil {
		t.Fatalf("Assertion failed: Expected the expectations to be loaded: %v", err)
	}

	for si := range suites {
		testSuite := &suites[si]

		rawManifest := &testSuite.Manifest
		manifest, err := parseManifestFromData(rawManifest.String(), "/path/to/project")
		if err != nil {
			t.Fatalf("failed to init pnp manifest for suite %d: %v", si, err)
		}

		for _, tc := range testSuite.Tests {
			parent := tspath.CombinePaths(tc.Importer, "fooo")
			pnpApi := &PnpApi{fs: osvfs.FS(), url: "/path/to/project/.pnp.cjs", manifest: manifest}

			t.Run(tc.It, func(t *testing.T) {
				t.Parallel()
				res, unqualifiedErr := pnpApi.ResolveToUnqualified(tc.Imported, parent)

				if tc.Expected == "error!" {
					if unqualifiedErr == nil {
						t.Fatalf("'%s': expected resolution to fail, got %q", tc.It, res)
					}
					return
				}

				if unqualifiedErr != nil {
					t.Fatalf("'%s': expected resolved path %q, got error: %v", tc.It, tc.Expected, unqualifiedErr.Message)
				}
				if res != tc.Expected {
					t.Fatalf("'%s': expected resolved path %q, got %q", tc.It, tc.Expected, res)
				}
			})
		}
	}
}

func TestResolveToUnqualifiedNormalizesPackageLocation(t *testing.T) {
	t.Parallel()

	manifest, err := parseManifestFromData(`{
		"dependencyTreeRoots": [{"name": "root", "reference": "workspace:."}],
		"enableTopLevelFallback": false,
		"fallbackPool": [],
		"fallbackExclusionList": [],
		"packageRegistryData": [
			["root", [["workspace:.", {
				"packageLocation": "./",
				"packageDependencies": [["pkg", "npm:1.0.0"]],
				"linkType": "SOFT"
			}]]],
			["pkg", [["npm:1.0.0", {
				"packageLocation": "./.yarn/cache/pkg/",
				"packageDependencies": [],
				"linkType": "HARD"
			}]]]
		]
	}`, "/path/to/project")
	if err != nil {
		t.Fatalf("failed to initialize PnP manifest: %v", err)
	}

	pnpApi := &PnpApi{manifest: manifest}
	for _, tc := range []struct {
		specifier string
		expected  string
	}{
		{specifier: "pkg", expected: "/path/to/project/.yarn/cache/pkg"},
		{specifier: "pkg/subpath", expected: "/path/to/project/.yarn/cache/pkg/subpath"},
		{specifier: "pkg/subpath/", expected: "/path/to/project/.yarn/cache/pkg/subpath"},
	} {
		t.Run(tc.specifier, func(t *testing.T) {
			t.Parallel()
			resolved, resolveErr := pnpApi.ResolveToUnqualified(tc.specifier, "/path/to/project/src/file.ts")
			if resolveErr != nil {
				t.Fatalf("expected %q to resolve, got error: %v", tc.specifier, resolveErr.Message)
			}
			if resolved != tc.expected {
				t.Fatalf("expected %q to resolve to %q, got %q", tc.specifier, tc.expected, resolved)
			}
		})
	}
}

func TestParseSinglePackageName(t *testing.T) {
	t.Parallel()
	pnpApi := &PnpApi{}
	name, _, err := pnpApi.ParseBareIdentifier("pkg")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if name != "pkg" {
		t.Fatalf("expected name %q, got %q", "pkg", name)
	}
}

func TestParseScopedPackageName(t *testing.T) {
	t.Parallel()
	pnpApi := &PnpApi{}
	name, _, err := pnpApi.ParseBareIdentifier("@scope/pkg")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if name != "@scope/pkg" {
		t.Fatalf("expected name %q, got %q", "@scope/pkg", name)
	}
}

func TestParsePackageNameWithLongSubpath(t *testing.T) {
	t.Parallel()
	pnpApi := &PnpApi{}
	name, modulePath, err := pnpApi.ParseBareIdentifier("pkg/a/b/c/index.js")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if name != "pkg" {
		t.Fatalf("expected name %q, got %q", "pkg", name)
	}
	if modulePath != "/a/b/c/index.js" {
		t.Fatalf("expected modulePath=%q, got %q", "a/b/c/index.js", modulePath)
	}
}

func TestParseScopedPackageWithLongSubpath(t *testing.T) {
	t.Parallel()
	pnpApi := &PnpApi{}
	name, modulePath, err := pnpApi.ParseBareIdentifier("@scope/pkg/a/b/c/index.js")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if name != "@scope/pkg" {
		t.Fatalf("expected name %q, got %q", "@scope/pkg", name)
	}
	if modulePath != "/a/b/c/index.js" {
		t.Fatalf("expected modulePath=%q, got %q", "a/b/c/index.js", modulePath)
	}
}
