//// [tests/cases/conformance/parser/ecmascript5/parserRealSource3.ts] ////

//// [parserRealSource3.ts]
// Copyright (c) Microsoft. All rights reserved. Licensed under the Apache License, Version 2.0. 
// See LICENSE.txt in the project root for complete license information.

///<reference path='typescript.ts' />

module TypeScript {
    // Note: Any addition to the NodeType should also be supported with addition to AstWalkerDetailCallback
    export enum NodeType {
        None,
        Empty,
        EmptyExpr,
        True,
        False,
        This,
        Super,
        QString,
        Regex,
        Null,
        ArrayLit,
        ObjectLit,
        Void,
        Comma,
        Pos,
        Neg,
        Delete,
        Await,
        In,
        Dot,
        From,
        Is,
        InstOf,
        Typeof,
        NumberLit,
        Name,
        TypeRef,
        Index,
        Call,
        New,
        Asg,
        AsgAdd,
        AsgSub,
        AsgDiv,
        AsgMul,
        AsgMod,
        AsgAnd,
        AsgXor,
        AsgOr,
        AsgLsh,
        AsgRsh,
        AsgRs2,
        ConditionalExpression,
        LogOr,
        LogAnd,
        Or,
        Xor,
        And,
        Eq,
        Ne,
        Eqv,
        NEqv,
        Lt,
        Le,
        Gt,
        Ge,
        Add,
        Sub,
        Mul,
        Div,
        Mod,
        Lsh,
        Rsh,
        Rs2,
        Not,
        LogNot,
        IncPre,
        DecPre,
        IncPost,
        DecPost,
        TypeAssertion,
        FuncDecl,
        Member,
        VarDecl,
        ArgDecl,
        Return,
        Break,
        Continue,
        Throw,
        For,
        ForIn,
        If,
        While,
        DoWhile,
        Block,
        Case,
        Switch,
        Try,
        TryCatch,
        TryFinally,
        Finally,
        Catch,
        List,
        Script,
        ClassDeclaration,
        InterfaceDeclaration,
        ModuleDeclaration,
        ImportDeclaration,
        With,
        Label,
        LabeledStatement,
        EBStart,
        GotoEB,
        EndCode,
        Error,
        Comment,
        Debugger,
        GeneralNode = FuncDecl,
        LastAsg = AsgRs2,
    }
}

/// [Declarations] ////



//// [parserRealSource3.d.ts]
declare namespace TypeScript {
    enum NodeType {
        None = 0,
        Empty = 1,
        EmptyExpr = 2,
        True = 3,
        False = 4,
        This = 5,
        Super = 6,
        QString = 7,
        Regex = 8,
        Null = 9,
        ArrayLit = 10,
        ObjectLit = 11,
        Void = 12,
        Comma = 13,
        Pos = 14,
        Neg = 15,
        Delete = 16,
        Await = 17,
        In = 18,
        Dot = 19,
        From = 20,
        Is = 21,
        InstOf = 22,
        Typeof = 23,
        NumberLit = 24,
        Name = 25,
        TypeRef = 26,
        Index = 27,
        Call = 28,
        New = 29,
        Asg = 30,
        AsgAdd = 31,
        AsgSub = 32,
        AsgDiv = 33,
        AsgMul = 34,
        AsgMod = 35,
        AsgAnd = 36,
        AsgXor = 37,
        AsgOr = 38,
        AsgLsh = 39,
        AsgRsh = 40,
        AsgRs2 = 41,
        ConditionalExpression = 42,
        LogOr = 43,
        LogAnd = 44,
        Or = 45,
        Xor = 46,
        And = 47,
        Eq = 48,
        Ne = 49,
        Eqv = 50,
        NEqv = 51,
        Lt = 52,
        Le = 53,
        Gt = 54,
        Ge = 55,
        Add = 56,
        Sub = 57,
        Mul = 58,
        Div = 59,
        Mod = 60,
        Lsh = 61,
        Rsh = 62,
        Rs2 = 63,
        Not = 64,
        LogNot = 65,
        IncPre = 66,
        DecPre = 67,
        IncPost = 68,
        DecPost = 69,
        TypeAssertion = 70,
        FuncDecl = 71,
        Member = 72,
        VarDecl = 73,
        ArgDecl = 74,
        Return = 75,
        Break = 76,
        Continue = 77,
        Throw = 78,
        For = 79,
        ForIn = 80,
        If = 81,
        While = 82,
        DoWhile = 83,
        Block = 84,
        Case = 85,
        Switch = 86,
        Try = 87,
        TryCatch = 88,
        TryFinally = 89,
        Finally = 90,
        Catch = 91,
        List = 92,
        Script = 93,
        ClassDeclaration = 94,
        InterfaceDeclaration = 95,
        ModuleDeclaration = 96,
        ImportDeclaration = 97,
        With = 98,
        Label = 99,
        LabeledStatement = 100,
        EBStart = 101,
        GotoEB = 102,
        EndCode = 103,
        Error = 104,
        Comment = 105,
        Debugger = 106,
        GeneralNode = 71,
        LastAsg = 41
    }
}

/// [Errors] ////

parserRealSource3.ts(4,21): error TS6053: File 'typescript.ts' not found.
parserRealSource3.ts(4,21): error TS9010: Reference directives are not supported in isolated declaration mode.
parserRealSource3.ts(116,9): error TS9007: Declaration emit for this file requires type resolution. An explicit type annotation may unblock declaration emit.
parserRealSource3.ts(117,9): error TS9007: Declaration emit for this file requires type resolution. An explicit type annotation may unblock declaration emit.


==== parserRealSource3.ts (4 errors) ====
    // Copyright (c) Microsoft. All rights reserved. Licensed under the Apache License, Version 2.0. 
    // See LICENSE.txt in the project root for complete license information.
    
    ///<reference path='typescript.ts' />
                        ~~~~~~~~~~~~~
!!! error TS6053: File 'typescript.ts' not found.
                        ~~~~~~~~~~~~~
!!! error TS9010: Reference directives are not supported in isolated declaration mode.
    
    module TypeScript {
        // Note: Any addition to the NodeType should also be supported with addition to AstWalkerDetailCallback
        export enum NodeType {
            None,
            Empty,
            EmptyExpr,
            True,
            False,
            This,
            Super,
            QString,
            Regex,
            Null,
            ArrayLit,
            ObjectLit,
            Void,
            Comma,
            Pos,
            Neg,
            Delete,
            Await,
            In,
            Dot,
            From,
            Is,
            InstOf,
            Typeof,
            NumberLit,
            Name,
            TypeRef,
            Index,
            Call,
            New,
            Asg,
            AsgAdd,
            AsgSub,
            AsgDiv,
            AsgMul,
            AsgMod,
            AsgAnd,
            AsgXor,
            AsgOr,
            AsgLsh,
            AsgRsh,
            AsgRs2,
            ConditionalExpression,
            LogOr,
            LogAnd,
            Or,
            Xor,
            And,
            Eq,
            Ne,
            Eqv,
            NEqv,
            Lt,
            Le,
            Gt,
            Ge,
            Add,
            Sub,
            Mul,
            Div,
            Mod,
            Lsh,
            Rsh,
            Rs2,
            Not,
            LogNot,
            IncPre,
            DecPre,
            IncPost,
            DecPost,
            TypeAssertion,
            FuncDecl,
            Member,
            VarDecl,
            ArgDecl,
            Return,
            Break,
            Continue,
            Throw,
            For,
            ForIn,
            If,
            While,
            DoWhile,
            Block,
            Case,
            Switch,
            Try,
            TryCatch,
            TryFinally,
            Finally,
            Catch,
            List,
            Script,
            ClassDeclaration,
            InterfaceDeclaration,
            ModuleDeclaration,
            ImportDeclaration,
            With,
            Label,
            LabeledStatement,
            EBStart,
            GotoEB,
            EndCode,
            Error,
            Comment,
            Debugger,
            GeneralNode = FuncDecl,
            ~~~~~~~~~~~
!!! error TS9007: Declaration emit for this file requires type resolution. An explicit type annotation may unblock declaration emit.
            LastAsg = AsgRs2,
            ~~~~~~~
!!! error TS9007: Declaration emit for this file requires type resolution. An explicit type annotation may unblock declaration emit.
        }
    }