//// [arrayMethodPredicates.ts]
var array: number[];
var readonlyArray: readonly number[];
var int8Array: Int8Array;
var uint8Array: Uint8Array;
var uint8ClampedArray: Uint8ClampedArray;
var int16Array: Int16Array;
var uint16Array: Uint16Array;
var int32Array: Int32Array;
var uint32Array: Uint32Array;
var float32Array: Float32Array;
var float64Array: Float64Array;
var bigInt64Array: BigInt64Array;
var bigUint64Array: BigUint64Array;

array.every(x => x);
readonlyArray.every(x => x);
int8Array.every(x => x);
uint8Array.every(x => x);
uint8ClampedArray.every(x => x);
int16Array.every(x => x);
uint16Array.every(x => x);
int32Array.every(x => x);
uint32Array.every(x => x);
float32Array.every(x => x);
float64Array.every(x => x);
bigInt64Array.every(x => x);
bigUint64Array.every(x => x);

array.filter(x => x);
readonlyArray.filter(x => x);
int8Array.filter(x => x);
uint8Array.filter(x => x);
uint8ClampedArray.filter(x => x);
int16Array.filter(x => x);
uint16Array.filter(x => x);
int32Array.filter(x => x);
uint32Array.filter(x => x);
float32Array.filter(x => x);
float64Array.filter(x => x);
bigInt64Array.filter(x => x);
bigUint64Array.filter(x => x);

array.find(x => x);
readonlyArray.find(x => x);
int8Array.find(x => x);
uint8Array.find(x => x);
uint8ClampedArray.find(x => x);
int16Array.find(x => x);
uint16Array.find(x => x);
int32Array.find(x => x);
uint32Array.find(x => x);
float32Array.find(x => x);
float64Array.find(x => x);
bigInt64Array.find(x => x);
bigUint64Array.find(x => x);

array.findIndex(x => x);
readonlyArray.findIndex(x => x);
int8Array.findIndex(x => x);
uint8Array.findIndex(x => x);
uint8ClampedArray.findIndex(x => x);
int16Array.findIndex(x => x);
uint16Array.findIndex(x => x);
int32Array.findIndex(x => x);
uint32Array.findIndex(x => x);
float32Array.findIndex(x => x);
float64Array.findIndex(x => x);
bigInt64Array.findIndex(x => x);
bigUint64Array.findIndex(x => x);

array.some(x => x);
readonlyArray.some(x => x);
int8Array.some(x => x);
uint8Array.some(x => x);
uint8ClampedArray.some(x => x);
int16Array.some(x => x);
uint16Array.some(x => x);
int32Array.some(x => x);
uint32Array.some(x => x);
float32Array.some(x => x);
float64Array.some(x => x);
bigInt64Array.some(x => x);
bigUint64Array.some(x => x);


//// [arrayMethodPredicates.js]
var array;
var readonlyArray;
var int8Array;
var uint8Array;
var uint8ClampedArray;
var int16Array;
var uint16Array;
var int32Array;
var uint32Array;
var float32Array;
var float64Array;
var bigInt64Array;
var bigUint64Array;
array.every(function (x) { return x; });
readonlyArray.every(function (x) { return x; });
int8Array.every(function (x) { return x; });
uint8Array.every(function (x) { return x; });
uint8ClampedArray.every(function (x) { return x; });
int16Array.every(function (x) { return x; });
uint16Array.every(function (x) { return x; });
int32Array.every(function (x) { return x; });
uint32Array.every(function (x) { return x; });
float32Array.every(function (x) { return x; });
float64Array.every(function (x) { return x; });
bigInt64Array.every(function (x) { return x; });
bigUint64Array.every(function (x) { return x; });
array.filter(function (x) { return x; });
readonlyArray.filter(function (x) { return x; });
int8Array.filter(function (x) { return x; });
uint8Array.filter(function (x) { return x; });
uint8ClampedArray.filter(function (x) { return x; });
int16Array.filter(function (x) { return x; });
uint16Array.filter(function (x) { return x; });
int32Array.filter(function (x) { return x; });
uint32Array.filter(function (x) { return x; });
float32Array.filter(function (x) { return x; });
float64Array.filter(function (x) { return x; });
bigInt64Array.filter(function (x) { return x; });
bigUint64Array.filter(function (x) { return x; });
array.find(function (x) { return x; });
readonlyArray.find(function (x) { return x; });
int8Array.find(function (x) { return x; });
uint8Array.find(function (x) { return x; });
uint8ClampedArray.find(function (x) { return x; });
int16Array.find(function (x) { return x; });
uint16Array.find(function (x) { return x; });
int32Array.find(function (x) { return x; });
uint32Array.find(function (x) { return x; });
float32Array.find(function (x) { return x; });
float64Array.find(function (x) { return x; });
bigInt64Array.find(function (x) { return x; });
bigUint64Array.find(function (x) { return x; });
array.findIndex(function (x) { return x; });
readonlyArray.findIndex(function (x) { return x; });
int8Array.findIndex(function (x) { return x; });
uint8Array.findIndex(function (x) { return x; });
uint8ClampedArray.findIndex(function (x) { return x; });
int16Array.findIndex(function (x) { return x; });
uint16Array.findIndex(function (x) { return x; });
int32Array.findIndex(function (x) { return x; });
uint32Array.findIndex(function (x) { return x; });
float32Array.findIndex(function (x) { return x; });
float64Array.findIndex(function (x) { return x; });
bigInt64Array.findIndex(function (x) { return x; });
bigUint64Array.findIndex(function (x) { return x; });
array.some(function (x) { return x; });
readonlyArray.some(function (x) { return x; });
int8Array.some(function (x) { return x; });
uint8Array.some(function (x) { return x; });
uint8ClampedArray.some(function (x) { return x; });
int16Array.some(function (x) { return x; });
uint16Array.some(function (x) { return x; });
int32Array.some(function (x) { return x; });
uint32Array.some(function (x) { return x; });
float32Array.some(function (x) { return x; });
float64Array.some(function (x) { return x; });
bigInt64Array.some(function (x) { return x; });
bigUint64Array.some(function (x) { return x; });
