//// [emitExponentiationOperator3.ts]
var temp: any;

delete --temp ** 3;
delete ++temp ** 3;
delete temp-- ** 3;
delete temp++ ** 3;
delete -++temp ** 3;
delete -temp++ ** 3;
delete -temp-- ** 3;

delete --temp ** 3 ** 1;
delete ++temp ** 3 ** 1;
delete temp-- ** 3 ** 1;
delete temp++ ** 3 ** 1;
delete -++temp ** 3 ** 1;
delete -temp++ ** 3 ** 1;
delete -temp-- ** 3 ** 1;;

<number>--temp ** 3;
<number>++temp ** 3;
<number>temp-- ** 3;
<number>temp++ ** 3;
<number>-++temp ** 3;
<number>-temp++ ** 3;
<number>-temp-- ** 3;

<number>--temp ** 3 ** 1;
<number>++temp ** 3 ** 1;
<number>temp-- ** 3 ** 1;
<number>temp++ ** 3 ** 1;
<number>-++temp ** 3 ** 1;
<number>-temp++ ** 3 ** 1;
<number>-temp-- ** 3 ** 1;

typeof --temp ** 3;
typeof temp-- ** 3;
typeof 3 ** 4;
typeof temp++ ** 4;
typeof temp-- ** 4;
typeof -3 ** 4;
typeof -++temp ** 4;
typeof -temp++ ** 4;
typeof -temp-- ** 4;

typeof --temp ** 3 ** 1;
typeof temp-- ** 3 ** 1;
typeof 3 ** 4 ** 1;
typeof temp++ ** 4 ** 1;
typeof temp-- ** 4 ** 1;
typeof -3 ** 4 ** 1;
typeof -++temp ** 4 ** 1;
typeof -temp++ ** 4 ** 1;
typeof -temp-- ** 4 ** 1;

void --temp ** 3;
void temp-- ** 3;
void 3 ** 4;
void temp++ ** 4;
void temp-- ** 4;
void -3 ** 4;
void -++temp ** 4;
void -temp++ ** 4;
void -temp-- ** 4;

void --temp ** 3 ** 1;
void temp-- ** 3 ** 1;
void 3 ** 4 ** 1;
void temp++ ** 4 ** 1;
void temp-- ** 4 ** 1;
void -3 ** 4 ** 1;
void -++temp ** 4 ** 1;
void -temp++ ** 4 ** 1;
void -temp-- ** 4 ** 1;

~ --temp ** 3;
~ temp-- ** 3;
~ 3 ** 4;
~ temp++ ** 4;
~ temp-- ** 4;
~ -3 ** 4;
~ -++temp ** 4;
~ -temp++ ** 4;
~ -temp-- ** 4;

~ --temp ** 3 ** 1;
~ temp-- ** 3 ** 1;
~ 3 ** 4 ** 1;
~ temp++ ** 4 ** 1;
~ temp-- ** 4 ** 1;
~ -3 ** 4 ** 1;
~ -++temp ** 4 ** 1;
~ -temp++ ** 4 ** 1;
~ -temp-- ** 4 ** 1;

! --temp ** 3;
! temp-- ** 3;
! 3 ** 4;
! temp++ ** 4;
! temp-- ** 4;
! -3 ** 4;
! -++temp ** 4;
! -temp++ ** 4;
! -temp-- ** 4;

! --temp ** 3 ** 1;
! temp-- ** 3 ** 1;
! 3 ** 4 ** 1;
! temp++ ** 4 ** 1;
! temp-- ** 4 ** 1;
! -3 ** 4 ** 1;
! -++temp ** 4 ** 1;
! -temp++ ** 4 ** 1;
! -temp-- ** 4 ** 1;

//// [emitExponentiationOperator3.js]
var temp;
delete Math.pow(--temp, 3);
delete Math.pow(++temp, 3);
delete Math.pow(temp--, 3);
delete Math.pow(temp++, 3);
delete -Math.pow(++temp, 3);
delete -Math.pow(temp++, 3);
delete -Math.pow(temp--, 3);
delete Math.pow(--temp, Math.pow(3, 1));
delete Math.pow(++temp, Math.pow(3, 1));
delete Math.pow(temp--, Math.pow(3, 1));
delete Math.pow(temp++, Math.pow(3, 1));
delete -Math.pow(++temp, Math.pow(3, 1));
delete -Math.pow(temp++, Math.pow(3, 1));
delete -Math.pow(temp--, Math.pow(3, 1));
;
Math.pow(--temp, 3);
Math.pow(++temp, 3);
Math.pow(temp--, 3);
Math.pow(temp++, 3);
-Math.pow(++temp, 3);
-Math.pow(temp++, 3);
-Math.pow(temp--, 3);
Math.pow(--temp, Math.pow(3, 1));
Math.pow(++temp, Math.pow(3, 1));
Math.pow(temp--, Math.pow(3, 1));
Math.pow(temp++, Math.pow(3, 1));
-Math.pow(++temp, Math.pow(3, 1));
-Math.pow(temp++, Math.pow(3, 1));
-Math.pow(temp--, Math.pow(3, 1));
typeof Math.pow(--temp, 3);
typeof Math.pow(temp--, 3);
typeof Math.pow(3, 4);
typeof Math.pow(temp++, 4);
typeof Math.pow(temp--, 4);
typeof -Math.pow(3, 4);
typeof -Math.pow(++temp, 4);
typeof -Math.pow(temp++, 4);
typeof -Math.pow(temp--, 4);
typeof Math.pow(--temp, Math.pow(3, 1));
typeof Math.pow(temp--, Math.pow(3, 1));
typeof Math.pow(3, Math.pow(4, 1));
typeof Math.pow(temp++, Math.pow(4, 1));
typeof Math.pow(temp--, Math.pow(4, 1));
typeof -Math.pow(3, Math.pow(4, 1));
typeof -Math.pow(++temp, Math.pow(4, 1));
typeof -Math.pow(temp++, Math.pow(4, 1));
typeof -Math.pow(temp--, Math.pow(4, 1));
void Math.pow(--temp, 3);
void Math.pow(temp--, 3);
void Math.pow(3, 4);
void Math.pow(temp++, 4);
void Math.pow(temp--, 4);
void -Math.pow(3, 4);
void -Math.pow(++temp, 4);
void -Math.pow(temp++, 4);
void -Math.pow(temp--, 4);
void Math.pow(--temp, Math.pow(3, 1));
void Math.pow(temp--, Math.pow(3, 1));
void Math.pow(3, Math.pow(4, 1));
void Math.pow(temp++, Math.pow(4, 1));
void Math.pow(temp--, Math.pow(4, 1));
void -Math.pow(3, Math.pow(4, 1));
void -Math.pow(++temp, Math.pow(4, 1));
void -Math.pow(temp++, Math.pow(4, 1));
void -Math.pow(temp--, Math.pow(4, 1));
~Math.pow(--temp, 3);
~Math.pow(temp--, 3);
~Math.pow(3, 4);
~Math.pow(temp++, 4);
~Math.pow(temp--, 4);
~-Math.pow(3, 4);
~-Math.pow(++temp, 4);
~-Math.pow(temp++, 4);
~-Math.pow(temp--, 4);
~Math.pow(--temp, Math.pow(3, 1));
~Math.pow(temp--, Math.pow(3, 1));
~Math.pow(3, Math.pow(4, 1));
~Math.pow(temp++, Math.pow(4, 1));
~Math.pow(temp--, Math.pow(4, 1));
~-Math.pow(3, Math.pow(4, 1));
~-Math.pow(++temp, Math.pow(4, 1));
~-Math.pow(temp++, Math.pow(4, 1));
~-Math.pow(temp--, Math.pow(4, 1));
!Math.pow(--temp, 3);
!Math.pow(temp--, 3);
!Math.pow(3, 4);
!Math.pow(temp++, 4);
!Math.pow(temp--, 4);
!-Math.pow(3, 4);
!-Math.pow(++temp, 4);
!-Math.pow(temp++, 4);
!-Math.pow(temp--, 4);
!Math.pow(--temp, Math.pow(3, 1));
!Math.pow(temp--, Math.pow(3, 1));
!Math.pow(3, Math.pow(4, 1));
!Math.pow(temp++, Math.pow(4, 1));
!Math.pow(temp--, Math.pow(4, 1));
!-Math.pow(3, Math.pow(4, 1));
!-Math.pow(++temp, Math.pow(4, 1));
!-Math.pow(temp++, Math.pow(4, 1));
!-Math.pow(temp--, Math.pow(4, 1));
