name: Setup Go
description: Setup Go

inputs:
  go-version:
    description: Go version to set up
    default: '1.26'

runs:
  using: composite

  steps:
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ inputs.go-version }}
        go-download-base-url: https://aka.ms/golang/release/latest
        cache: false
