name: Setup Go
description: Setup Go

inputs:
  go-version:
    description: Go version to set up
    default: '1.27'

runs:
  using: composite

  steps:
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ inputs.go-version }}
        go-download-base-url: https://aka.ms/golang/release/latest
        cache: false

    - name: Cache Go modules
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ~/go/pkg/mod
        key: go-modules-${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-${{ inputs.go-version }}-${{ hashFiles('**/go.mod', '**/go.sum', 'go.work', 'go.work.sum', '.custom-gcl.yml') }}
