// Code generated by tools/scripts/tsc/generate-enums.ts from tsc/internal/tspath/path.go. DO NOT EDIT.
export var CaseSensitivity: any;
(function (CaseSensitivity) {
    CaseSensitivity[CaseSensitivity["Insensitive"] = 0] = "Insensitive";
    CaseSensitivity[CaseSensitivity["Sensitive"] = 1] = "Sensitive";
})(CaseSensitivity || (CaseSensitivity = {}));
