// Code generated by tools/scripts/tsc/generate-enums.ts from tsc/internal/execute/incremental/snapshot.go. DO NOT EDIT.
export var FileEmitKind: any;
(function (FileEmitKind) {
    FileEmitKind[FileEmitKind["None"] = 0] = "None";
    FileEmitKind[FileEmitKind["Js"] = 1] = "Js";
    FileEmitKind[FileEmitKind["JsMap"] = 2] = "JsMap";
    FileEmitKind[FileEmitKind["JsInlineMap"] = 4] = "JsInlineMap";
    FileEmitKind[FileEmitKind["DtsErrors"] = 8] = "DtsErrors";
    FileEmitKind[FileEmitKind["DtsEmit"] = 16] = "DtsEmit";
    FileEmitKind[FileEmitKind["DtsMap"] = 32] = "DtsMap";
})(FileEmitKind || (FileEmitKind = {}));
