// Code generated by tools/scripts/tsc/generate-enums.ts from tsc/internal/module/types.go. DO NOT EDIT.
export var ImportPhase: any;
(function (ImportPhase) {
    ImportPhase[ImportPhase["Evaluation"] = 0] = "Evaluation";
    ImportPhase[ImportPhase["Source"] = 1] = "Source";
})(ImportPhase || (ImportPhase = {}));
