// Code generated by tools/scripts/generate-enums.mjs from tsc/internal/checker/types.go. DO NOT EDIT.
export var IndexKind: any;
(function (IndexKind) {
    IndexKind[IndexKind["String"] = 0] = "String";
    IndexKind[IndexKind["Number"] = 1] = "Number";
})(IndexKind || (IndexKind = {}));
