// Code generated by tools/scripts/tsc/generate-enums.ts from tsc/internal/core/compileroptions.go. DO NOT EDIT.

export enum ModuleDetectionKind {
    None = 0,
    Auto = 1,
    Legacy = 2,
    Force = 3,
}
