// Code generated by tools/scripts/tsc/generate-enums.ts from tsc/internal/core/compileroptions.go. DO NOT EDIT.
export var NewLineKind: any;
(function (NewLineKind) {
    NewLineKind[NewLineKind["None"] = 0] = "None";
    NewLineKind[NewLineKind["CRLF"] = 1] = "CRLF";
    NewLineKind[NewLineKind["LF"] = 2] = "LF";
})(NewLineKind || (NewLineKind = {}));
