// Code generated by Herebyfile.mjs generate:enums from internal/compiler/emitter.go. DO NOT EDIT.
export var EmitOnly: any;
(function (EmitOnly) {
    EmitOnly[EmitOnly["All"] = 0] = "All";
    EmitOnly[EmitOnly["OnlyJs"] = 1] = "OnlyJs";
    EmitOnly[EmitOnly["OnlyDts"] = 2] = "OnlyDts";
})(EmitOnly || (EmitOnly = {}));
