// Code generated by tools/scripts/tsc/generate-options.ts. DO NOT EDIT.

package transpile

import "github.com/microsoft/TypeScript/tsc/internal/core"

func clearOptionsForTranspile(options *core.CompilerOptions) {
	options.AllowImportingTsExtensions = core.TSUnknown
	options.Composite = core.TSUnknown
	options.EmitDeclarationOnly = core.TSUnknown
	options.Declaration = core.TSUnknown
	options.DeclarationDir = ""
	options.Incremental = core.TSUnknown
	options.Lib = nil
	options.NoEmit = core.TSUnknown
	options.NoEmitOnError = core.TSUnknown
	options.Paths = nil
	options.RootDirs = nil
	options.TsBuildInfoFile = ""
	options.Types = nil
	options.OutFile = ""
}
