//go:build ignore

package main

import (
	"bytes"
	"cmp"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"log"
	"maps"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"unicode"

	"github.com/microsoft/TypeScript/tsc/internal/collections"
	"github.com/microsoft/TypeScript/tsc/internal/json"
	"golang.org/x/text/language"
)

type diagnosticMessage struct {
	Category           string `json:"category"`
	Code               int    `json:"code"`
	ReportsUnnecessary bool   `json:"reportsUnnecessary"`
	ReportsDeprecated  bool   `json:"reportsDeprecated"`
	// spelling error here is [sic] in Strada
	ElidedInCompatibilityPyramid bool `json:"elidedInCompatabilityPyramid"`

	key string
}

type localizationProject struct {
	Projects []struct {
		LocItems []struct {
			Languages string `json:"Languages"`
		} `json:"LocItems"`
	} `json:"Projects"`
}

func main() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)

	diagnosticsOutput := flag.String("diagnostics", "", "path to the output diagnostics_generated.go file")
	localesOutput := flag.String("locales", "", "path to the output localizations_generated.go file")
	localeDir := flag.String("localedir", "", "path to the localized diagnostic JSON files")
	locProject := flag.String("locproject", "", "path to LocProject.json")
	locSourceOutput := flag.String("locsource", "", "path to the English localization source file")
	flag.Parse()

	if *diagnosticsOutput == "" || *localesOutput == "" || *localeDir == "" || *locProject == "" || *locSourceOutput == "" {
		flag.Usage()
		return
	}

	rawDiagnosticMessages := readRawMessages("diagnosticMessages.json")
	diagnosticMessages := slices.Collect(maps.Values(rawDiagnosticMessages))

	slices.SortFunc(diagnosticMessages, func(a *diagnosticMessage, b *diagnosticMessage) int {
		return cmp.Compare(a.Code, b.Code)
	})

	diagnosticsBuf := generateDiagnostics(diagnosticMessages)

	formatted, err := format.Source(diagnosticsBuf.Bytes())
	if err != nil {
		log.Fatalf("failed to format diagnostics output: %v", err)
		return
	}

	if err := os.WriteFile(*diagnosticsOutput, formatted, 0o666); err != nil {
		log.Fatalf("failed to write diagnostics output: %v", err)
		return
	}

	localeNames := readLocaleNames(*locProject, *localeDir)
	localesBuf := generateLocalizations(localeNames)
	formatted, err = format.Source(localesBuf.Bytes())
	if err != nil {
		log.Fatalf("failed to format localizations output: %v", err)
		return
	}
	if err := os.WriteFile(*localesOutput, formatted, 0o666); err != nil {
		log.Fatalf("failed to write localizations output: %v", err)
		return
	}

	locSource, err := generateLocalizationSource(diagnosticMessages)
	if err != nil {
		log.Fatalf("failed to generate localization source: %v", err)
		return
	}

	if err := os.MkdirAll(filepath.Dir(*locSourceOutput), 0o755); err != nil {
		log.Fatalf("failed to create localization source directory: %v", err)
		return
	}
	if err := os.WriteFile(*locSourceOutput, locSource, 0o666); err != nil {
		log.Fatalf("failed to write localization source: %v", err)
		return
	}
}

func generateDiagnostics(diagnosticMessages []*diagnosticMessage) *bytes.Buffer {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by generate.go; DO NOT EDIT.\n")
	buf.WriteString("\n")
	buf.WriteString("package diagnostics\n")

	for _, m := range diagnosticMessages {
		varName, key := convertPropertyName(m.key, m.Code)

		fmt.Fprintf(&buf, "var %s = &Message{code: %d, category: Category%s, key: %q, text: %q", varName, m.Code, m.Category, key, m.key)

		if m.ReportsUnnecessary {
			buf.WriteString(`, reportsUnnecessary: true`)
		}
		if m.ElidedInCompatibilityPyramid {
			buf.WriteString(`, elidedInCompatibilityPyramid: true`)
		}
		if m.ReportsDeprecated {
			buf.WriteString(`, reportsDeprecated: true`)
		}

		buf.WriteString("}\n\n")
	}

	buf.WriteString("func keyToMessage(key Key) *Message {\n")
	buf.WriteString("\tswitch key {\n")
	for _, m := range diagnosticMessages {
		_, key := convertPropertyName(m.key, m.Code)
		varName, _ := convertPropertyName(m.key, m.Code)
		fmt.Fprintf(&buf, "\tcase %q:\n\t\treturn %s\n", key, varName)
	}
	buf.WriteString("\tdefault:\n\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")

	return &buf
}

func readLocaleNames(projectPath string, localeDir string) []string {
	file, err := os.Open(projectPath)
	if err != nil {
		log.Fatalf("failed to open localization project: %v", err)
	}
	defer file.Close()

	var project localizationProject
	if err := json.UnmarshalRead(file, &project); err != nil {
		log.Fatalf("failed to decode localization project: %v", err)
	}
	if len(project.Projects) != 1 || len(project.Projects[0].LocItems) != 1 {
		log.Fatalf("expected exactly one project with one localization item in %s", projectPath)
	}

	languages := strings.Split(project.Projects[0].LocItems[0].Languages, ";")
	declared := make(map[string]bool, len(languages))
	for _, localeName := range languages {
		tag, err := language.Parse(localeName)
		if err != nil {
			log.Fatalf("invalid locale %q in %s: %v", localeName, projectPath, err)
		}
		if canonical := tag.String(); canonical != localeName {
			log.Fatalf("locale %q in %s is not canonical; use %q", localeName, projectPath, canonical)
		}
		if declared[localeName] {
			log.Fatalf("duplicate locale %q in %s", localeName, projectPath)
		}
		declared[localeName] = true
	}

	entries, err := os.ReadDir(localeDir)
	if err != nil {
		log.Fatalf("failed to read locale directory: %v", err)
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".json" {
			continue
		}
		if !strings.HasSuffix(entry.Name(), ".generated.json") {
			log.Fatalf("locale file %q must use the .generated.json suffix", filepath.Join(localeDir, entry.Name()))
		}
		localeName := strings.TrimSuffix(entry.Name(), ".generated.json")
		if !declared[localeName] {
			log.Fatalf("locale file %q is not declared in %s", filepath.Join(localeDir, entry.Name()), projectPath)
		}
		delete(declared, localeName)
	}
	if len(declared) != 0 {
		missing := slices.Sorted(maps.Keys(declared))
		log.Fatalf("locales declared in %s have no handback files: %s", projectPath, strings.Join(missing, ", "))
	}

	return languages
}

func generateLocalizations(localeNames []string) *bytes.Buffer {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by generate.go; DO NOT EDIT.\n\n")
	buf.WriteString("package diagnostics\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"sync\"\n\n")
	buf.WriteString("\t\"golang.org/x/text/language\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("var localeNames = []string{\n")
	buf.WriteString("\t\"en\",\n")
	for _, localeName := range localeNames {
		fmt.Fprintf(&buf, "\t%q,\n", localeName)
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var matcher = language.NewMatcher([]language.Tag{\n")
	buf.WriteString("\tlanguage.English,\n")
	for _, localeName := range localeNames {
		fmt.Fprintf(&buf, "\tlanguage.MustParse(%q),\n", localeName)
	}
	buf.WriteString("})\n\n")

	buf.WriteString("var localeFuncs = []func() map[Key]string{\n")
	buf.WriteString("\tnil,\n")
	for _, localeName := range localeNames {
		fmt.Fprintf(&buf, "\tsync.OnceValue(func() map[Key]string { return loadLocaleData(%q) }),\n", localeName)
	}
	buf.WriteString("}\n")

	return &buf
}

func generateLocalizationSource(diagnosticMessages []*diagnosticMessage) ([]byte, error) {
	var messages collections.OrderedMap[string, string]
	for _, m := range diagnosticMessages {
		_, key := convertPropertyName(m.key, m.Code)
		messages.Set(key, m.key)
	}
	data, err := json.MarshalIndent(&messages, "", "    ")
	return append(data, '\n'), err
}

func readRawMessages(p string) map[int]*diagnosticMessage {
	file, err := os.Open(p)
	if err != nil {
		log.Fatalf("failed to open file: %v", err)
		return nil
	}
	defer file.Close()

	var rawMessages map[string]*diagnosticMessage
	if err := json.UnmarshalRead(file, &rawMessages); err != nil {
		log.Fatalf("failed to decode file: %v", err)
		return nil
	}

	codeToMessage := make(map[int]*diagnosticMessage, len(rawMessages))
	for k, m := range rawMessages {
		m.key = k
		if existing, ok := codeToMessage[m.Code]; ok {
			log.Fatalf("diagnostics %q and %q both use code %d", existing.key, k, m.Code)
		}
		codeToMessage[m.Code] = m
	}

	return codeToMessage
}

var (
	multipleUnderscoreRegexp           = regexp.MustCompile(`_+`)
	leadingUnderscoreUnlessDigitRegexp = regexp.MustCompile(`^_+(\D)`)
	trailingUnderscoreRegexp           = regexp.MustCompile(`_$`)
)

func convertPropertyName(origName string, code int) (varName string, key string) {
	var b strings.Builder
	b.Grow(len(origName))

	for _, r := range origName {
		switch r {
		case '*':
			b.WriteString("_Asterisk")
		case '/':
			b.WriteString("_Slash")
		case ':':
			b.WriteString("_Colon")
		default:
			if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
				b.WriteRune('_')
			} else {
				b.WriteRune(r)
			}
		}
	}

	varName = b.String()
	// get rid of all multi-underscores
	varName = multipleUnderscoreRegexp.ReplaceAllString(varName, "_")
	// remove any leading underscore, unless it is followed by a number.
	varName = leadingUnderscoreUnlessDigitRegexp.ReplaceAllString(varName, "$1")
	// get rid of all trailing underscores.
	varName = trailingUnderscoreRegexp.ReplaceAllString(varName, "")

	key = varName
	if len(key) > 100 {
		key = key[:100]
	}
	key = key + "_" + strconv.Itoa(code)

	if !token.IsExported(varName) {
		var b strings.Builder
		b.Grow(len(varName) + 2)
		if varName[0] == '_' {
			b.WriteString("X")
		} else {
			b.WriteString("X_")
		}
		b.WriteString(varName)
		varName = b.String()
	}

	if !token.IsIdentifier(varName) || !token.IsExported(varName) {
		log.Fatalf("failed to convert property name to exported identifier: %q", origName)
	}

	return varName, key
}
