name: Accept Baselines, Fix Lints, and Format

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  update:
    runs-on: ubuntu-latest
    environment:
      name: azure
      deployment: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - uses: ./.github/actions/setup-go
      - name: Update generated files and baselines
        run: |
          git config user.email "290192711+typescript-automation[bot]@users.noreply.github.com"
          git config user.name "typescript-automation[bot]"
          npm ci
          npx hereby generate
          npx hereby test || true
          npx hereby baseline-accept
          npx hereby lint --fix
          npx hereby format
          git add tsc packages tools
          git diff --cached
          git commit -m "Update generated files, baselines, lints, and formatting"
      - uses: azure/login@7ddb5af1ef8758cf1353cf3b42f940aee27ba21c # v3.0.2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: Create GitHub App token
        id: app-token
        uses: microsoft/create-github-app-token-via-key-vault@5ba0d436e9c3cac52feff4d1f2f66f9698ce4a2d # v1
        with:
          client-id: ${{ vars.TYPESCRIPT_AUTOMATION_GITHUB_APP_CLIENT_ID }}
          key-id: ${{ vars.TYPESCRIPT_AUTOMATION_GITHUB_APP_KEY_ID }}
          owner: microsoft
          repositories: TypeScript
          permission-contents: write
      - name: Configure GitHub App token
        env:
          GITHUB_APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          basic_auth="$(node -e 'process.stdout.write(Buffer.from("x-access-token:" + process.env.GITHUB_APP_TOKEN).toString("base64"))')"
          echo "::add-mask::$basic_auth"
          git config --local http.https://github.com/.extraheader "AUTHORIZATION: basic ${basic_auth}"
      - run: git push
